### ISSUE TITLE
Introduce maven wrapper to ensure correct version (was: CNFE)

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#103]
Since the 1.2 release, I cannot build locally anymore (1.3.0-SNAPSHOT). Can anyone confirm? I am sure I didn't change anything ...

... well I did change something, I updated my central maven to 3.3.9. I do not know why, but the build fails with 3.3.9 and java 1.8.0_66 on osx ...

Lets introduce maven wrapper https://github.com/takari/maven-wrapper/blob/master/README.md to allow easy project specific maven version setups.

**Comment by meyerdan** [comment]
Hi Jan,

I was able to build it successfully. My configuration:

```
meyerd@ca-meyerd camunda-bpm-spring-boot-starter $ mvn --version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: /home/meyerd/Programs/apache-maven-3.1.1
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /home/meyerd/Programs/jdk1.8.0_91/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-87-generic", arch: "amd64", family: "unix"
```
