### ISSUE TITLE
Webapps not starting for ProcessEngineName with special characters

### ISSUE THREAD

**Issue by mixaaaa** [camunda/camunda-bpm-spring-boot-starter#104]
`camunda.bpm.process-engine-name=sample-service` is not working when loading `localhost:50100/app/cockpit/index.html` using webapps. The redirection loads `http://localhost:50100/app/cockpit/sample-service/`.

Instead `camunda.bpm.process-engine-name=sample` works and the redirection will lead to `http://localhost:50100/app/cockpit/sample/#/login`. Still have no idea why this happens ;)

**Comment by jangalinski** [comment]
Sounds like a bug to me ... will have to investigate

**Comment by hawky-4s-** [comment]
Not a spring-boot-starter issue, instead the Camunda webapp is unable to work with process-engines containing special chars.
See https://app.camunda.com/jira/browse/CAM-3500

**Comment by mixaaaa** [comment]
Did not see that. I'm sorry ;)
