### ISSUE TITLE
Should reactor extension be integrated?

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#105]
@jangalinski: Just noticed that the [camunda reactor extension](https://github.com/camunda/camunda-bpm-reactor) provides a spring configuration. Wouldn't it be a good idea to integrate this with the starter or at least give a hint in readme or docs?

**Comment by jangalinski** [comment]
Could you test the spring configuration of the reactor extension? Though the example works, We had trouble integrating it into our application. So currently this is a "hidden, still to be evaluated" feature.
Would also be nice if you could check if devtools influence the result.

If the above works, there is no need to integrate with the starter extension, the plugin will just be used when you have camunda-reactor-starter on the classpath.

**Comment by jangalinski** [comment]
I just retested with a new empty project: adding a dependency to  camunda-bpm-reactor-spring-starter automatically activates the plugin. So there is no need to add it to this starter. I will close this issue ...
