### ISSUE TITLE
Auto-deployment doesn't work for Fat-Jar

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-bpm-spring-boot-starter#106]
In 1.2.0, the auto-deployment doesn't work when the application is packaged in a Fat-Jar. It works for unit tests and if you start the application from IDE as java application. The application class looks like

```
@SpringBootApplication
public class ExampleProcessApplication {

  public static void main(String[] args) {
    SpringApplication.run(ExampleProcessApplication.class, args);
  }

  @Autowired
  private RuntimeService runtimeService;

  @PostConstruct
  public void startProcess() {
    runtimeService.startProcessInstanceByKey("process");
  }

}
```

If you run the jar then the application fails because the engine find no deployed process. The same code works for version 1.1.0. See the attached [example](https://github.com/camunda/camunda-bpm-spring-boot-starter/files/351754/spring-boot-example.zip).

**Comment by osteinhauer** [comment]
Hi @saig0.

Thank you for reporting.

If you cannot wait for next release: as a workaround for you the only idea I have is to define your own ``org.camunda.bpm.spring.boot.starter.configuration.CamundaDeploymentConfiguration`` bean as it is implemented in commit e805313.
