### ISSUE TITLE
Patch release 1.2.1

### ISSUE THREAD

**Issue by hawky-4s-** [camunda/camunda-bpm-spring-boot-starter#107]
Hi @jangalinski , @osteinhauer ,

I would propose a 1.2.1 patch release with the last 3 fixes we did.
WDYT?
Maybe we can also fix #93 for it?

Cheers,
Christian

see https://github.com/camunda/camunda-bpm-spring-boot-starter/milestone/5?closed=1

**Comment by osteinhauer** [comment]
👍🏻

**Comment by jangalinski** [comment]
Which fixes would that be?

* #106 
* #102 

and ... ?

anyhow: of course, patching is a good idea.

**Comment by osteinhauer** [comment]
- #106 
- #102 
- #101 

don't know much about #93

**Comment by jangalinski** [comment]
just fixed #93

**Comment by osteinhauer** [comment]
saturday fixing morning 😉

**Comment by jangalinski** [comment]
added a link to the closed issues in 1.2.1 to the OP, I am good to go.

I did not really understand how not implementing ProcessEngineServices anymore fixed the devtools issue. Could you add some detail to the issue? I have been a big fan of using the interface for the bean configuration and woulld have to change that ... do you know "why" this is helping?

**Comment by jangalinski** [comment]
#88 was fixed as well ... since it a security risk, we should add it to 1.2.1 aas well ... I edited the milestone flag

**Comment by hawky-4s-** [comment]
Done.

**Comment by jangalinski** [comment]
Thanks Christian ... I got a lot of failing/logrunning build-emails ... do we have problems with our ci?
