### ISSUE TITLE
Different compiler level for extensions and examples

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#114]
For now we have compiler level 1.6 for extensions and examples. The compiling JDK must be greater 1.7 (see discussion in #98). 

We can safely switch to:

- Compiling with JDK 1.8
- Compiler level 1.6 for extensions
- Compiler level 1.8 for examples

**Comment by osteinhauer** [comment]
@hawky-4s- could you please verify if branch https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/different_jdks is ready for use with Jenkins? If OK, you can merge the pom changes into master and remove the branch.

**Comment by jangalinski** [comment]
You mean overwriting java.version in the example parent pom? But can I set different levels in my multi maven module setup in IDE?

**Comment by osteinhauer** [comment]
Overwriting java.version is correct. Seems I am not able to express what I mean, sorry. Did you checked the branch?

**Comment by jangalinski** [comment]
No sorry, other stuff to do, just tracking mails. But why not considering leaving everything as is (jdk6/7) and doing a big bang jdk8 only with 2.0 as I suggested? I do not really get the benefit of the dual strategy. I mean with a stable 1.3 release, jdk6 people "could" still use the extension, but we would make clear that we continue with java8 only .... I though that was agreed on.

**Comment by hawky-4s-** [comment]
@jangalinski : I created a second build for the branch

**Comment by osteinhauer** [comment]
Had some time this morning so I checked the examples jdk6 compatibility. Result: For now they need at least jdk7. This is at least because of h2 version 1.4.192 defined in spring boot boms [which is jdk7 compiled](https://github.com/h2database/h2database/issues/300). Because we are using jdk7 to compile and run the test we haven't noticed this when upgrading spring boot versions.

IMHO there are 2 solutions:

1. Overriding default versions of dependencies so examples will run on jdk6 again.
2. Switch to jdk8 in examples like the branch above.

Solution 1 has the disadvantage that we cannot verify unless using jdk6 in Jenkins. 
Solution 2 is very simple and has the advantage to stay jdk6 compatible in extensions without making false promises in our examples.

With both solutions one can build applications with jdk6.

I prefer solution 2.

I should do this sooner.

**Comment by jangalinski** [comment]
isn't this fixed now?
