### ISSUE TITLE
Camunda REST API endpoint

### ISSUE THREAD

**Issue by pnegri** [camunda/camunda-bpm-spring-boot-starter#116]
Hello guys, after following the camunda-spring-boot-starter-example-web example, I cant find the REST API.

Can any1 help me? Shouldn't API be available at http://localhost:8080/api/engine/default/process-definition ?

**Comment by jangalinski** [comment]
/api/ is only used internally by the webapp.

The rest api should be http://localhost:8080/rest/engine/default/process-definition ?

it is an open issue to document this, see #110

**Comment by pnegri** [comment]
Previous to /api/ I tried to use the /rest/

Jan, can you take a look here please?
https://github.com/pnegri/camunda-rest-server-example

What I am doing wrong?

**Comment by osteinhauer** [comment]
When using starter version 1.2.1 you have to define a bean like

```
@Bean
public ResourceConfig jerseyConfig() {
    return new CamundaJerseyResourceConfig();
}
```
See the [dmn rest example](https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/1.2.1/examples/camunda-spring-boot-starter-example-dmn-rest/src/main/java/org/camunda/bpm/spring/boot/starter/example/dmn/rest/DmnRestApplication.java).

In version 1.3.0 this won't be necessary anymore.

**Comment by pnegri** [comment]
Thanks. I will try it.

**Comment by pnegri** [comment]
Worked. Thanks a lot guys :)
