### ISSUE TITLE
Upgrade to Spring Boot 1.4

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#117]
https://spring.io/blog/2016/07/28/spring-boot-1-4-released

**Comment by artild** [comment]
Just found some incompatibility when try to upgrade my project with **camunda-bpm-spring-boot-starter-webapp** to Spring Boot 1.4.

Class **o.c.b.s.b.s.w.CamundaBpmWebappAutoConfiguration extends o.s.b.a.w.WebMvcAutoConfiguration.WebMvcAutoConfigurationAdapter**, and that class was changed, moved all autowired properties to constructor, and that's cause error **"There is no default constructor available ..."**

I tried in my project exclude o.c.b.s.b.s.w.CamundaBpmWebappAutoConfiguration from auto-configuration and just added copy of this class but extends from WebMvcConfigurerAdapter.
And it seems to be working.

**Comment by jangalinski** [comment]
Since this seems to require some manual work, I would suggest to keep it out of the 1.3 release and do this together with the jdk8 introducion in 2.0

**Comment by osteinhauer** [comment]
I agree. With d4e33f7 the starter is more clean but there is no guarantee that it will work without changes. So if somebody switches to 1.4 manual work may be necessary.

**Comment by jangalinski** [comment]
on branch release200 i did the refactorings mentioned in https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#test-utilities-and-classes

I had some failing tests that I had to ignore:

[ ] CamundaJpaAutoConfigurationIT.transactionTest
[ ] DmnRestApplicationTest 
[ ] CamundaBpmActuatorIT
[ ] CamundaBpmRestIT
[ ] CamundaBpmRestConfigurationIT
[ ] SimpleApplicationTest

need fixing before we can continue

**Comment by osteinhauer** [comment]
tests are fixed
