### ISSUE TITLE
Authorizations not working

### ISSUE THREAD

**Issue by mikehalma** [camunda/camunda-bpm-spring-boot-starter#118]
Hi,

Great work - I was hoping that Camunda would adopt Spring Boot themselves.

I have found that authorisation permissions are not being applied.  To reproduce:

- Clone this project
- Go into examples/camunda-spring-boot-starter-example-webapp
- Run the app with command "mvn spring-boot:run"
- Navigate to localhost:8080/app/admin/index.html
- Create an admin user
- Log into the admin app with the admin user
- Create a new user.  Do not give the user permission to do anything.
- Log out
- Log into the admin app with the new user - this should not be allowed, but it is
- In the admin app, the new user has permission to do absolutely anything

Cheers,
Mike.

**Comment by mikehalma** [comment]
Hmm I've been reading about the [authorisation service](https://github.com/camunda/camunda-docs-manual/blob/master/content/user-guide/process-engine/authorization-service.md) and it says that by default configuration option "authorizationEnabled" is set to false.

I think this property used to be set in processes.xml.  Should I implement a CamundaProcessEngiineConfiguration and put it there?  How does that work?

**Comment by jangalinski** [comment]
Ah, ok. We currently have two ways of starting the webapp ... with and without extending the SpringBootProcessApplication.
If you work without (and I guess thats what the example does), the processes.xml defaults are not used. If you extends the processApplication, they are used. Imho (still need to discuss), we should switch to ProcessApplication only, because otherwise embedded forms do not work as well ...

**Comment by mikehalma** [comment]
I tried this but it didn't work.  I changed WebappExampleApplication to the following:

```
@SpringBootApplication
@ProcessApplication
public class WebappExampleApplication extends SpringBootProcessApplication {

  public static void main(String... args) {
    SpringApplication.run(WebappExampleApplication.class, args);
  }
}

```

and created src/main/resources/META-INF/processes.xml:

```
<process-application
xmlns="http://www.camunda.org/schema/1.0/ProcessApplication"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<process-archive name="loan-approval">
  <process-engine>default</process-engine>
  <properties>
    <property name="authorizationEnabled">true</property>
    <property name="isDeleteUponUndeploy">false</property>
    <property name="isScanForProcessDefinitions">true</property>
  </properties>
</process-archive>

</process-application>
```

but I still have the same issue.

I feel that I must be doing something stupid as authorisations seem pretty important in order to use Camunda seriously.  I agree with you that ProcessApplication is a sensible default as I cannot think of a use case where you would not need authorisations.

Any ideas?

**Comment by osteinhauer** [comment]
Just tried to debug the `SecurityFilter`. Maybe the default `/securityFilterRules.json` coming with `camunda-webapp-webjar-7.5.0.jar` is a point to look for. IMHO it is hard to understand why or when `EngineRequestAuthorizer` and `ApplicationRequestAuthorizer` are used.

**Comment by osteinhauer** [comment]
OMG.

Just added `configuration.setAuthorizationEnabled(true);` and authorizations worked as far I could see.

For current SNAPSHOT I will add a property which defaults to `true`.

**Comment by osteinhauer** [comment]
@mikehalma Before closing the issue: would you like to verify?

**Comment by mikehalma** [comment]
Looks good to me.

Thank you very much!

**Comment by sourabhparsekar** [comment]
In case of a springboot app, we can add property `camunda.bpm.authorization.enabled = true` to enable authorization. However, I noticed that, any change to Authorization in Admin section require camunda process engine restart to take effect.
