### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#120]
see https://github.com/camunda/camunda-bpm-spring-boot-starter/milestone/4?closed=1

**Comment by jangalinski** [comment]
I think we got enough goodies for the next release. Objections?

**Comment by osteinhauer** [comment]
I would include #127 as last goodie.

**Comment by osteinhauer** [comment]
IMHO we are ready to release

**Comment by hawky-4s-** [comment]
Assign me, when we are ready.

**Comment by hawky-4s-** [comment]
Created CAM-6650 for this.

**Comment by jangalinski** [comment]
Any news?

**Comment by hawky-4s-** [comment]
Done.
