### ISSUE TITLE
Using lombok for CamundaBpmProperties

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#123]
There is still a lot of configurtaion we do not support via yaml. When we take the road to full support and stick to our current style, the CamundaBpmProperties will become unmaintainable. 

I would suggest introducing lombok Data for this class, so we can leave out all those boring getters/setters.

Opinions?

**Comment by jangalinski** [comment]
see https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/lombok_for_properties

**Comment by osteinhauer** [comment]
👍🏻

**Comment by osteinhauer** [comment]
Hi Jan. Do you have experiences with [delombok](https://projectlombok.org/features/delombok.html)? Using this we could reduce the boiler plate without adding a new transitive dependency.

**Comment by jangalinski** [comment]
Not so far. But for the simple objects we are using it should not be too hard.

I was also thinking about moving the configuration/plugin stuff to a separate module. I started working with plugins to group configuration topics in my current project as well and this could become somehow a "camunda-bpm-configuration" extension of its own later, so it can be used without spring boot.
Not saying I want to create the extension right away, but separating the aspect might be a good idea.
