### ISSUE TITLE
Catching MismatchingMessageCorrelationException still leads to roll back

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#126]
I have a simple process `o-UserTaskA-sendEvent-UserTaskB-O`

The sendEvent uses a JavaDelegate that tries a non existing message name and catches the exception:

```java
public void execute(DelegateExecution execution) throws Exception {
        try {
          execution.getProcessEngineServices().getRuntimeService().correlateMessage("foo");
        }  catch (Exception e) {
          logger.info("========================================== ignoring failed correlation {}", e.getMessage());
        }
      }
```

In a plain (StandAloneInMemory) example, this leads to UserTaskB waiting because the sendEvent is passed succesfully.
With a SpringBootApplication using the starter, it fails, because somehow the transaction is marked as rollback although the exception was caught.

```
016-08-08 22:15:31.667  INFO 51520 --- [  restartedMain] ication$$EnhancerBySpringCGLIB$$baf0e4f9 : ========================================== ignoring failed correlation Cannot correlate message 'foo': No process definition or execution matches the parameters
2016-08-08 22:15:31.695 ERROR 51520 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only
```
I am not sure if this is related to teh spring-boot starter or if this ís a general issue of camunda&spring. But I would like to get a fix, because this is a valid use case imho, the only workaround would be to query message subscribers before correlating an event. Opinions? Ideas?

**Comment by osteinhauer** [comment]
Hi Jan. IMHO this is how transactions with unchecked exceptions works. There is a help full [blogpost](http://codetreasury.com/2014/01/25/springs-transactional-important-points/). Hope this helps.

**Comment by jangalinski** [comment]
Sorry, forgot about this. I already reproduced this using plain engine-spring setup. So it is not related to this extension.
It's odd however that using plain SE, it works.  I think we need to come up with a solution, but on platform side.
