### ISSUE TITLE
Configuration of default serialization format

### ISSUE THREAD

**Issue by RomanSchloemmer** [camunda/camunda-bpm-spring-boot-starter#127]
The configuration of the engine's default serialization format should be possible in a convenient and straight forward way.

**Comment by jangalinski** [comment]
Thank you!

note: enhance the CamundaBpmProperties config to accept serilization format via yaml/properties

**Comment by osteinhauer** [comment]
Where in properties should this be located? `camunda.bpm.default-serialization-format` or `camunda.bpm.database.default-serialization-format`?

**Comment by jangalinski** [comment]
I would say: top-level, its spin-, not db-specific.

**Comment by Marco-Sulla** [comment]
What's the default value? In the docs it's simply said "Camunda default".......... :D

**Comment by Marco-Sulla** [comment]
Hello?

**Comment by jangalinski** [comment]
Default is java object serialization. (Serializable).  Questions like this are better suited for the forum
