### ISSUE TITLE
switch to jdk 1.6

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#13]
After some discussion we agreed to keep this on the camunda default 1.6 for now, which means we must edit the maven and project settings and check if anything beyond 1.6 was used so far.

<del>since we have to leave the camunda default jdk 1.6 any way due to spring boot, wouldn't it be a good idea to walk the whole mile and just get on with 1.8? 
I would believe that whoever works with spring boot is not bound to a close-to-outdated jdk level and we would gain all the cool features (lamdas, functional interfaces, suppliers, ...).</del>

**Comment by osteinhauer** [comment]
I would prefer to use 1.8 features but in a weak moment I have set the version to 1.7.

Spring boot [recommends](http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-build-systems.html) to use something newer to 1.6 but is still 1.6 compatible.

In fact this starter should "only" configure some beans. The question should be: use 1.6 or 1.8?

**Comment by osteinhauer** [comment]
IMHO what we should do is: use 1.6 for camunda-spring-boot-starter and 1.8 for examples.

**Comment by meyerdan** [comment]
+1 for maintaining 1.6 compatibility.

**Comment by jangalinski** [comment]
Ok, but when we stick to 1.6 i would vote against two different jdks in this repo.  Messes up ide and maven.  The examples should not need much code anyway, so they would not benefit enough to justify the extra efford.  Later we could provide 1.8 examples in a different setup.

**Comment by osteinhauer** [comment]
ok. use 1.6 only.

**Comment by jangalinski** [comment]
I edited this issue to reflect that decision

**Comment by jangalinski** [comment]
I am having trouble when writing a test that uses the Spring-Test Runner, because it does a component scan and fails on the provided servlet-2.4 jar which requires Java 7.

Seems like we need to change the embedded tomcat: http://docs.spring.io/spring-boot/docs/1.2.4.RELEASE/reference/htmlsingle/#howto-use-java-6

I will switch to tomcat 7 for testing http://docs.spring.io/spring-boot/docs/1.2.4.RELEASE/reference/htmlsingle/#howto-use-tomcat-7

**Comment by osteinhauer** [comment]
Hi Jan. Can you provide an example?

**Comment by jangalinski** [comment]
I will commit my failing attempt as a branch tonight

**Comment by jangalinski** [comment]
I do not need an example:

This is what I get when I start example-web/Application http://pastebin.com/gcjWZeGX

This is what I get when I run the CamundaBpmRestIT http://pastebin.com/nUwwwVQi

Seems to me like stated above that with the springweb bundle we either need >=Java7 or switch to tomcat 7. 

Does this work on your machines?

**Comment by jangalinski** [comment]
My opinion: JDK6 has been outdated for a while now. I understand why camunda has to support the core product for 1.6, but I dont believe that anyone considering a Spring-Boot/microservice environment will use 1.6. So we should drop legacy support and create something new and shiny. I'd even prefer to go to 1.8 so we can use the language features. Besides: 1.7 is unsupported as of July 15.

**Comment by osteinhauer** [comment]
I have adjusted the maven dependencies with a "java6" profile which can be removed when using a later version. In fact this is the same discussion as above: at compile time java version 1.6 is fine. But I accept @jangalinski that versions later than 1.6 will be used at runtime.

So I would still prefer to divide the starter (1.6), starter integration tests (1.8) and examples (1.8 )to have a clean setup.

**Comment by hawky-4s-** [comment]
I would propose to use the maven based activation instead of applying activeByDefault on the jdk6 profile. I am ok with using JDK 8 for the example, but the starter should stay 1.6.

**Comment by osteinhauer** [comment]
Activation by jdk would be fine.

**Comment by osteinhauer** [comment]
@hawky-4s- would you please verify that the verify goal is in the build pipeline? Without the *IT tests will not be executed. So there will be early feedback if everything is fine for jdk 1.6

**Comment by osteinhauer** [comment]
cool. THX!

**Comment by jangalinski** [comment]
A lot of trouble to go through just to keep 1.6 ... but the ITests are working now. How do you develop right now? Is the project in your IDE set to 1.6 or 1.8?

**Comment by osteinhauer** [comment]
My IDE (Eclipse) compiles with 1.6 and executes with 1.8.

**Comment by hawky-4s-** [comment]
Could all please test if this works for you with JDK6? I am unable to run the complete project on OSX because the Apple JDK6 breaks with PermGen Space. Same on our Jenkins when using Oracle JDK6.

**Comment by jangalinski** [comment]
not before 21h ...

**Comment by osteinhauer** [comment]
I have tested successfully with running maven 3 on jdk 8 and let the compiler and test plugins run with jdk 6. There is a profile to specify the jdk. 

Cause I am in vacation I am unable to give more details for now.

**Comment by hawky-4s-** [comment]
Okay, works.
