### ISSUE TITLE
history level should default to "auto"

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#130]
I just set up a springboot/webapp application against an existing db ... failed due to different history-levels. Then I switched to "auto" and it worked.

I suggest making "auto" the default for spring boot apps ... if the db is not configured so far, "auto" will result in "audit" (the camunda default) anyway, but it safes the trouble of adding the config to the yaml if it is not.

**Comment by menski** [comment]
Please be aware that there a multiple null pointer exceptions with history level auto (see [CAM-5164](https://app.camunda.com/jira/browse/CAM-5164), [CAM-5165](https://app.camunda.com/jira/browse/CAM-5165)). But maybe they are not triggered in your setup.

**Comment by yanavasileva** [comment]
Moved to CAM-10015
