### ISSUE TITLE
configure jenkins build to work with java8 only 

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#131]
With 2.0.0, no special configuration for examples and extension should be used anymore.

**Comment by jangalinski** [comment]
sorry

**Comment by osteinhauer** [comment]
IMHO this should already have been done @hawky-4s- ?

**Comment by hawky-4s-** [comment]
The current job is using java8 already. Dunno about the special config etc., haven't done anything on that part.

**Comment by jangalinski** [comment]
Then I got this wrong ... will close
