### ISSUE TITLE
create blogpost/release note for 1.3.0

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#133]
we should show the world on blog.camunda.org what we build, since there where a lot of important fixes and at least one breaking change (configuration vs. plugin)

**Comment by osteinhauer** [comment]
You're right! Wasn't there any hint how to write/contribute a blog post?

**Comment by jangalinski** [comment]
see readme on https://github.com/camunda/blog.camunda.org

**Comment by osteinhauer** [comment]
Hi Jan. 

I wrote a first [draft](https://github.com/osteinhauer/blog.camunda.org/blob/master/content/post/2016/09/camunda-spring-boot-1.3.0-released.md). Because I start in the holiday I want to ask you to review, finish and publish the post and check that the release is done. 

Thx!

**Comment by jangalinski** [comment]
Will do. Thanks and have a nice vacation ...

**Comment by jangalinski** [comment]
created https://github.com/camunda/blog.camunda.org/pull/16

**Comment by jangalinski** [comment]
published, see: https://blog.camunda.org/post/2016/09/09/camunda-spring-boot-1.3.0-released/
