### ISSUE TITLE
Documentation is not generated or pushed

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#135]
Just compared [source](https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/docs/src/main/asciidoc/properties.adoc) and [output](https://camunda.github.io/camunda-bpm-spring-boot-starter/docs/master/index.html#properties) and found mismatching content.

**Comment by jangalinski** [comment]
I changed the ascii doc so

1. we use includes to separate the large index.adoc into smaller parts
2. I changed the properties table to use "prefix"+"property" which makes it more readable and makes it clearer which properties belong together

The source already uses that pattern, the result is still the old format. So I guess the create doc never ran.

**Comment by osteinhauer** [comment]
You're right, the complete content is outdated. I changed the title. @hawky-4s- can you have a look?

**Comment by hawky-4s-** [comment]
I had a look at it, there was a problem with the configuration of the publish-docs.sh script inside the Jenkins job. It got the wrong input value, which resulted in copying the new docs to new directories named like the commit hash.
It should work now.

**Comment by hawky-4s-** [comment]
Works now.
