### ISSUE TITLE
use the new github simplified docs publishing

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#136]
Instead of handling the gh-pages branch, github now alloes using /docs directly: https://github.com/blog/2228-simpler-github-pages-publishing

Maybe its a good Idea to switch?

**Comment by hawky-4s-** [comment]
Took a short glance at it and it might be a bit simpler but not much.

**Comment by jangalinski** [comment]
so we stick to the plan
