### ISSUE TITLE
use travis ci

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#141]
currently a non-public camunda server is used for building. In case of error, non-camunda-members do not have access.. we should move at least the ci and nightly build to travis so every member of this github org has access.

**Comment by jangalinski** [comment]
@hawky-4s-   I need admin rights on this repo to activate travis  .... could you a) give me these rights (seems I have them already for example on camunda-bpm-reactor) or b) enable travis for this repo?

**Comment by hawky-4s-** [comment]
Activated TravisCI

**Comment by hawky-4s-** [comment]
In the future a Community Jenkins will be publicly available with GitHub Pull Request building, notification etc.

**Comment by jangalinski** [comment]
Behold: https://travis-ci.org/camunda/camunda-bpm-spring-boot-starter
