### ISSUE TITLE
Minimal camunda-springboot-rest app fails to start with circular dependency between 5 beans in the application context on creating datasource

### ISSUE THREAD

**Issue by olafrauch** [camunda/camunda-bpm-spring-boot-starter#148]
Hi guys,

first of all: Congrats for getting the camunda award on the Camunda community day. Nice work 👍 

On preparing a minimal springboot camunda project I came across the following issue:

As soon as I add the camunda-bpm-spring-boot-starter-rest dependency, the startup of the app fails with a `circular dependency between 5 beans`.

As soon as I add a @Autowired dependency to the Camunda RuntimeService the error is gone.

Attached a simple demonstrator project.

The version of camunda or the camunda spring boot starter does not make difference.

As it is a cornercase, it is only annoying, but there may be a deeper cause worth digging into.

Cheers
Olaf

---

[koala-playground-springboot.zip](https://github.com/camunda/camunda-bpm-spring-boot-starter/files/483473/koala-playground-springboot.zip)

```
2016-09-20 21:34:09.530 ERROR 14896 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

There is a circular dependency between 5 beans in the application context:
        - dataSource defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Dbcp.class]
        - processEngineFactoryBean defined in class path resource [org/camunda/bpm/spring/boot/starter/CamundaBpmAutoConfiguration.class]
        - processEngineConfigurationImpl defined in class path resource [org/camunda/bpm/spring/boot/starter/CamundaBpmConfiguration.class]
        - camundaDatasourceConfiguration (field protected org.springframework.transaction.PlatformTransactionManager org.camunda.bpm.spring.boot.starter.configuration.impl.DefaultDatasourceConfiguration.transactionManager)
        - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration$DataSourceTransactionManagerConfiguration
        - dataSource
```

**Comment by jangalinski** [comment]
Hi Olaf. Thanks for the kind words. I will have a look at it asap, but probably not before tomorrow night. Jan

**Comment by jangalinski** [comment]
So, I some small check ... I can confirm this happens with 2.0.0-SNAPSHOT and Spring Boot 1.4.0 so this is a bug in the current snapshot we have to fix.
It does not occur with 1.3.0 and Spring Boot 1.3.7, so we do not have to rush and hotfix the release.

I will add teh bug flag. If you yourself happen to find a solution: gladly except pull requests, but I will have a look into this as well.

**Comment by jangalinski** [comment]
This can be fixed by adding `@EnableProcessApplication` to the app.
