### ISSUE TITLE
Create documentation infrastructure

### ISSUE THREAD

**Issue by hawky-4s-** [camunda/camunda-bpm-spring-boot-starter#15]
In order to write good documentation I propose to use a combination of Asciidoc + Maven + GitHub pages to publish the docs for the users.
I would take care of the infrastructure for it.

**Comment by osteinhauer** [comment]
+1

**Comment by osteinhauer** [comment]
@hawky-4s- please enable the documentation publishing in the build pipeline

**Comment by osteinhauer** [comment]
The github pages is still on snapshot version. There should be the release version.

**Comment by hawky-4s-** [comment]
It currently pushes always the latest version. Dunno about what it should
be.

**Comment by osteinhauer** [comment]
Maybe we could have a structure like http://docs.spring.io/spring-boot/docs/ with a current link for the latest release.



> Am 04.09.2015 um 11:04 schrieb hawky-4s- <notifications@github.com>:
> 
> It currently pushes always the latest version. Dunno about what it should
> be.
>
