### ISSUE TITLE
Request: Camunda boot within own context

### ISSUE THREAD

**Issue by BePe2** [camunda/camunda-bpm-spring-boot-starter#150]
Hi,

It would be nice, if we could run camunda boot  in it's own context. Right now we run our own angular App incl. REST calls, camunda rest & camunda web in the same (Servlet-)context, which leads  to some config issues (since also our REST Api makes use of "/lib", "/api", etc). 

An additional context (like spring-boot does with the property "management.context-path") would be really appreciated

regards
Ben

**Comment by jangalinski** [comment]
Hi Ben

I am not that into angular dev ... can you provide an example?

Thanks
Jan

**Comment by BePe2** [comment]
Hi Jan,

It's not angular specific. The "problem" is that the camunda webapp grabs URLs like "/api", "/app" and "lib" and adds an own Securityfilter if the requested URL starts with before mentioned urls.

This means that localhost:8080/app is taken by camunda and (worse) localhost:8080/api also adds the camunda security Filter.

So it would be nice if it may be possible to run the camunda webcontext within an own ServletContext (like http://localhost/camunda) and the camunda webprojects (cockpit, etc) would register themselves under http://localhost/camunda/app , http://localhost/camunda/api and so on.

Just a hint regarding multiple contexts: http://stackoverflow.com/questions/29096511/using-multiple-dispatcher-servlets-web-contexts-with-spring-boot

I guess the CamundaBpmWebappAutoConfiguration class has to be adjusted though, whereas CamundaBpmWebappInitializer doesn't need refactoring (since onStartup would have a servletContext parameter). Just thinking ;-)

tnx & regards
Ben

**Comment by jangalinski** [comment]
We should have this in 2.0 ... I think its quite easy when I look at https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/starter-webapp/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.java

```
@Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/lib/**").addResourceLocations("classpath:/lib/");
    registry.addResourceHandler("/api/**").addResourceLocations("classpath:/api/");
    registry.addResourceHandler("/app/**").addResourceLocations("classpath:/app/");
    super.addResourceHandlers(registry);
  }

  @Override
  public void addViewControllers(ViewControllerRegistry registry) {
    if (isIndexRedirectEnabled) {
      registry.addRedirectViewController("/", "/app/");
    }
    super.addViewControllers(registry);
  }
```

**Comment by berndruecker** [comment]
Just a hint: For me it did not work as Jan described. But maybe you have more luck on it :-)

**Comment by jangalinski** [comment]
You are right .... the real work is done in https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/starter-webapp/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java

**Comment by berndruecker** [comment]
Yes - I adjusted this as well ;-) But hey - as written - maybe I just messed it up. That's why I created an issue insted of a Pull Request...

**Comment by jangalinski** [comment]
I remember taht I was working on that a while ago ... but then reverted it because I thought: no one will ever want to change the path ... :-)

**Comment by berndruecker** [comment]
Is there any chance somebody looks as this any time soon? As I surrendered I will find a way around in my scenario otherwiese ;-)

**Comment by jangalinski** [comment]
I can check it this week.

**Comment by berndruecker** [comment]
THAT would be AWESOME. I repeat: AWESOME!!!!!

**Comment by jangalinski** [comment]
Sorry Bernd, first have to fix the webjar vas 1.4 issue ... hopefully I still find some time on the weekend.

**Comment by berndruecker** [comment]
OK - please let me know when you proceed (or when you give up ;-)).

**Comment by jangalinski** [comment]
I have the strange feeling, that my webjar issue is related ... if the webjar context is corectly loaded via the spring-boot-webjar loader, it seems we do not need most of the fancy filter settings in the starter. Will investigate and verify

**Comment by berndruecker** [comment]
Any news?

**Comment by jangalinski** [comment]
Not really ... we are still struggling. Camunda itself is not really prepared to share its context with another application. We still have some ideas left, but time is the issue ...

**Comment by jangalinski** [comment]
Patrick spent some time on this again on friday ... without success ... we are not giving up yet, but it's far from beeing solved and I would not block a 2.0.0 release waiting for this.
Maybe some of your webapp guys could join?

**Comment by berndruecker** [comment]
Thanks for the the hard work and the feedback! Seems to be a hard thing to do. As I still also have other issues in the Spring Boot environment I will most probably switch to a WildFly + WAR environment which is dockerized nicely. That means I think I will ditch my personal Spring Boot experiments soon :-/ From the company side we have no customer requests for Spring Boot yet, so kind of hard to assign any resources to it (especially with the 7.6 coming up soon).

**Comment by jangalinski** [comment]
Thats totally understandable ... we just had to debug and reverse engineer a lot to understand how the webapp works. Its not really a common stack. For me personally, although we already support two customer projects using spring boot, having anything besides camunda-webapp and embedded forms on the spring-node has not been a relevant use case, so I would prefer to solve more urgent issues first ...

I guess we will come up with concrete webapp implementation questions and ask them on the forum, than we can see if we get any more valuable information ...

**Comment by berndruecker** [comment]
Good plan!

**Comment by Dredalious** [comment]
Any updates on this?
We're a bit in the same position, having an app that uses /api path already and integrated camunda embedded engine in an own way (just the engine), we now want to switch this integration to the spring boot starter (as it's way better and enabled the use of the cockpit), but the /api path conflict is holding us a bit back. 

PS: We got redirected to this project from Camunda and we have enterprise support, so there is some interest in spring boot integration, but probably from the smaller clients ;-)

**Comment by Dredalious** [comment]
A quick update, we haven't found a real solution for this. We worked around it by freeing some endpoints: /api/(cockpit|admin|tasklist|engine) and we've documented these internally to avoid these endpoints being used by our application.
We did not secure the endpoints in our application, leaving this starter/the camunda part, it seems to take care of that.
In our use case, we have a nginx proxy in front of our application and we deny any public traffic to those endpoints (and /app) anyway as it's only for internal housekeeping/monitoring.
We're now testing this setup to see if there are no side effects (primarily security config that gets mingled) but it seems to be all right.

**Comment by jangalinski** [comment]
I have an offer from a camunda developer to help with this, but this has to wait til next week cause they where busy with the 7.7 release. Hopefully we will gain some insight how the webapp works with the endpoints and can improve this.

**Comment by jangalinski** [comment]
I will move this to the next milestone ... no support for this with 2.2 unfortunately

**Comment by sdorokhova** [comment]
Copied the ticket to Jira: https://app.camunda.com/jira/browse/CAM-8302
Please continue discussion there.

**Comment by jangalinski** [comment]
Not that I am aware of ...

**Comment by reyolivo** [comment]
I believe this will solve it:
In your application.properties file add the following!

server.servlet.context-path=/camunda #or whatever base url you want

You can also change the port:
server.port=8765

**Comment by Felix-Indoing** [comment]
I don't think this is a possible solution as it will redirect all @RestController under that context path.

**Comment by nik-sta** [comment]
Hey guys, any updates on this issue? Trying currently to achieve the same lol xD

**Comment by berndruecker** [comment]
From what I see in JIRA this should be fixed by https://jira.camunda.com/browse/CAM-11373 - @botscripter - could you maybe check and confirm? Then I could also close this issue before it turns 5 :-)
