### ISSUE TITLE
Authorizations (still) not working

### ISSUE THREAD

**Issue by joehm** [camunda/camunda-bpm-spring-boot-starter#151]
@jangalinski Re: #118 - I cannot confirm. Authorization are still not working for me. I still have the same behavior as initially described in #118. Tried with and without explicit camunda.bpm.authorization.enabled: true and with the default 7.5.0 webjar that comes with the starter as well as a custom built webjar 7.5.4-ee as described by Bernd Rücker @ https://github.com/camunda/camunda-consulting/tree/master/snippets/camunda-webapp-webjar-ee. No success :-/

**Comment by jangalinski** [comment]
Have to verify if this is still a problem, should have been solved by setting the authorization property to true

**Comment by jangalinski** [comment]
checked with latest 2.0.0-SNAPSHOT and Authorization enabled set to true. Works on my machine.   Please provide a complete failing example so we can analyse.
