### ISSUE TITLE
c-b-s-b-s-test: switch to assertj version 3.6.x

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#164]
Spring-starter-test now comes with the mighty and useful assertj library. But they still use 2.5.0, which is limited to Java 7 and does not support asserting Optionals for example.
Since this extension requires Java8 from 2.0.0 on, we should switch to the latest (currently 3.5.2) version of assertj.

**Comment by jangalinski** [comment]
Turns out this is harder than expected ... see http://stackoverflow.com/questions/40496407/spring-boot-starter-test-1-4-1-use-assertj-core-3-5-x/40496858#40496858

I keep getting 2.5.0 and 3.5.2 dependencies ...

**Comment by jangalinski** [comment]
I am not able to do so. Since the bpm-assert extension wont be easily moved to jdk8 and assertj > 2.x the only option is to exclude assertj completely and require users of the camunda-bpm-spring-boot-starter-test to explicitly add a dependency to assertj.

**Comment by jangalinski** [comment]
Seems not to be possible .. moved this to milestone 3.0 ... spring boot 2 will hopefully support this

**Comment by berndruecker** [comment]
Even 2.5 make problems, see https://github.com/camunda/camunda-bpm-assert/issues/90. Seems only 1.7.1 is safe so far.

**Comment by sdorokhova** [comment]
Copied to https://app.camunda.com/jira/browse/CAM-8296.
Please continue discussion in Jira.
