### ISSUE TITLE
Remove ProcessApplication annotation on EnableProcessApplication

### ISSUE THREAD

**Issue by karuniko** [camunda/camunda-bpm-spring-boot-starter#167]
Hi,
I'm trying to start simple springboot autoconfigured embedded process engine on a [supported](https://docs.camunda.org/manual/7.5/introduction/supported-environments/) web server like Wildfly 10 for instance. I'm NOT using process application, just embedded process engine and that's it. I'm deploying spring boot app in a WAR file (meaning use of SpringBootServletInitializer).
The error I'm getting while application is being deployed is:
ENGINE-07014 Class 'interface org.camunda.bpm.spring.boot.starter.annotation.EnableProcessApplication' is annotated with @org.camunda.bpm.application.ProcessApplication but is not a subclass of org.camunda.bpm.application.AbstractProcessApplication
Could you please try to understand what's wrong could be here?

camunda version: 7.5.6-ee
camunda spring boot: 2.0.0-SNAPSHOT
app server: Wildfly 10.2.0
java: sun 1.8.0_66

P.S It works perfectly on a plain tomcat.

Regards,
Dmitry

**Comment by jangalinski** [comment]
Hi Dmitry I removed the annotation from EnableProcessApplication. It was a leftover from an experiment, so thanks for reporting.
