### ISSUE TITLE
make taskexecutor configurable

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#168]
see https://forum.camunda.org/t/concurrent-execution-of-multipe-jobs-from-the-same-process-with-spring-boot/1956/12

By default, parallel execution is not possible because taskExecutor uses one thread. This can be manually overwritten by 

```
@Bean
public TaskExecutor taskExecutor() {
  ThreadPoolTaskExecutor threadPoolTaskExecutor = new ThreadPoolTaskExecutor();
  threadPoolTaskExecutor.setCorePoolSize(10);
  return threadPoolTaskExecutor;
}
```

but it would be a good option to allow setting the core pool size via yaml.

**Comment by hawky-4s-** [comment]
We should add this to the 2.0.0 release

**Comment by jangalinski** [comment]
so far, only corePoolSize can be set via camunda.bpm.job-execution.core-pool-size. More to follow
