### ISSUE TITLE
write documentation

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#17]
Write documentation in asciidoc. See [index.adoc](https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/camunda-spring-boot-starter-docs/src/main/asciidoc/index.adoc).

**Comment by osteinhauer** [comment]
I have written some doc. Because it is my "implementation guy" view it would be great to get somebody else for review, correct and enhance with other point of views. Thanks.

**Comment by meyerdan** [comment]
Look good. I think it provides the most important information to users who want to start on a project.

**Comment by lofidewanto** [comment]
Maybe you can add information about where to find the webapps, something like:

localhost:9010/context/app/admin/index.html
localhost:9010/context/app/tasklist/index.html
localhost:9010/context/app/cockpit/index.html

**Comment by larbigj** [comment]
Please add a section about the context path of the REST API in the documentation
http://localhost:8080/camunda/app/tasklist/default/ does not work :-(

**Comment by jangalinski** [comment]
can this be closed? I mean, we have documentation and we should have more concrete issues that we really work on instead one open issue that goes on and on ...

**Comment by hawky-4s-** [comment]
Think so.

**Comment by osteinhauer** [comment]
👍🏻
