### ISSUE TITLE
Add new Welcome page to WebappStarter

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-spring-boot-starter#170]
Here https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java#L56

is missing: 

    servletContext.addListener(new org.camunda.bpm.welcome.impl.web.bootstrap.WelcomeContainerBootstrap.WelcomeContainerBootstrap()());

**Comment by jangalinski** [comment]
Does the  WelcomeContainer exist in 7.5.0? I cannot find the class ....

**Comment by berndruecker** [comment]
It is introduced with 7.6 - sorry I missed to mention that.

Sent from my FairPhone

Am 22.11.2016 17:11 schrieb Jan Galinski <notifications@github.com>:

Does the WelcomeContainer exist in 7.5.0? I cannot find the class ....

**Comment by berndruecker** [comment]
Thanks a lot!
