### ISSUE TITLE
clarify usage of property datasource.tablePrefix

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#177]
The property is not supported by camunda and leads to confusion. If we decide to support it, we should have an additional issue for the implementation, until this I vouch for removal.

see http://stackoverflow.com/questions/40989183/camunda-spring-boot-starter-create-database-in-schema-not-working

**Comment by ThorbenLindhauer** [comment]
Note that the engine configuration property `databaseTablePrefix` is useful in Camunda and supported. It simply does not work in combination with `databaseSchemaUpdate` set to `create` or `create-drop`, i.e. the engine won't respect the `databaseTablePrefix` when it creates the tables.

**Comment by jangalinski** [comment]
Ah, nice hint ... I was already wondering why we have the switch at all. So I guess we will leave it in but print a warning if used with schema-update.
