### ISSUE TITLE
add pschalk to the repo

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#179]
@hawky-4s- my colleague Patrick started working on this project as well. Could you add him as a member, so he can interact with the repo directly? Thanks.

**Comment by pschalk** [comment]
Are there any updates to this?

**Comment by meyerdan** [comment]
I sent Jan the corporate CLA today.

**Comment by jangalinski** [comment]
You just received a company CLA ... so please go ahead!

**Comment by hawky-4s-** [comment]
Invitation sent.
