### ISSUE TITLE
overwriting camunda.version does not work (in banner)

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#19]
I am setting up an example project to test the release candidate. My pom defines camunda.version=7.4.0-SNAPSHOT.

But when I start up a simple SpringBoot application, the banner reads "v7.3.0".

I did not check so far whether this is just an issue with the banner or if I am hard-coded to the 7.3 version.

**Comment by hawky-4s-** [comment]
Probably an issue with the banner. It is filtered during the build to
add the version. My bad! Will fix it!

**Comment by jangalinski** [comment]
perfect.

**Comment by jangalinski** [comment]
For now I just removed the camunda version
