### ISSUE TITLE
Just adding the webapp dependency does not work

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-spring-boot-starter#191]
If you create a plain project and do this (taken from the main readme) it does not work - I think because it uses a much too old Spring version. I had to use the BOM instead. 

<dependency>
  <groupId>org.camunda.bpm.extension.springboot</groupId>
  <artifactId>camunda-bpm-spring-boot-starter([-rest|-webapp])</artifactId>
  <version>2.0.0</version>
</dependency>

readme should be updated to make getting started easier

**Comment by jangalinski** [comment]
I do not get the point ... the example-webapp does exactly that ... adding the starter-webapp and run.

if you want to use another camunda version you unfortunately have to provide the full camunda-bom again, but that's also documented.

Maybe you could the missing docs-passage (via vcomment/PR or directly)?

**Comment by sdorokhova** [comment]
If I got the point, it seems to be working fine in v. 2.3.0-alpha1.
Example is here: https://github.com/camunda/camunda-bpm-examples/tree/master/spring-boot-starter/example-webapp
Getting started is here: https://docs.camunda.org/get-started/spring-boot/project-setup/
Closing the issue. Feel free to open the new issue in [JIRA](https://app.camunda.com/jira/browse/CAM).
