### ISSUE TITLE
Exchange engine rest api the webapp is using

### ISSUE THREAD

**Issue by pschalk** [camunda/camunda-bpm-spring-boot-starter#194]
Since I've already needed this feature, and there are also requests in the camunda forum, it would be a good idea to implement this feature in the starter-webapp. 
(https://forum.camunda.org/t/exchange-rest-api-the-webapp-is-using/1463/3)

Dev Hint: Maybe by extending the ProcessEnginesFilter?

**Comment by sdorokhova** [comment]
Copied to https://app.camunda.com/jira/browse/CAM-8295.
Please continue working on this in Jira.
