### ISSUE TITLE
introduce git-flow-like dev-process

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#199]
I have the feeling thats its confusing for users that the master branch shown on github does not reflect the latest released version but instead the current development snapshot.
I would propose to go into the direction of git flow http://nvie.com/posts/a-successful-git-branching-model/
So master always contains the latest release, and snapshot is developed in "development" branch. We then merge feature branches to develop. When it comes to releases, we have to see if we really need release-branches or if we just merge the final state to master and release from there. Thats why I call it "flow-like".

Benefits: code, examples and readme shown on github in the default view work with the latest central repo version, ongoing development is better separated.
Requirements: we need an additional build pipeline for develop and we need to document the new approach so we do not get pull-request contriubutions to master.

Opinions?

**Comment by sdorokhova** [comment]
Hi @jangalinski ,
I like the idea, but it seems to be not relevant any more, as Spring Boot Starter will now follow the Camunda practices, which imply development in master branch. 
Will close the issue then.
