### ISSUE TITLE
example-web is not reachable via browser

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#20]
The ITest works, but when I start the application itself and open http://localhost:8080/engine/default/process-definition I get a 404. Is there something wrong with the starter or am I missing something? I did do any configuration, just started the Application

**Comment by jangalinski** [comment]
OK, will give it a try. Few questions though:

* why is the path with "engine" correctly resolved in the ITest? What is different when the SpringRunner starts the application?
* If my spring-boot-process-app serves forms or exposes other api via REST, shouldn't we have a clear separation of paths? 
* Where and how can I configure this? I just found the RestConfiguration and it seems to be "magic".
* Wouldn't it be great to have this in the docs (both starter-docs and example readme? (don't get me wrong: I can take over documenting this (when I understood how it works).

**Comment by jangalinski** [comment]
OK, thanks. Do we agree that solving this (= having an easy, clean and well documented way of activating camundas REST API) is a crucial milestone for the first release?

**Comment by jangalinski** [comment]
Could you please start the example-web application and try to reach it via Browser? I tried all possible combinations I could think of, but all I get is 404. I guess the example is broken (in a way that there is something in the test scope that lets it work).

**Comment by osteinhauer** [comment]
I am in vacation, so I am just happy to get some mails...test it latest when I am back

**Comment by osteinhauer** [comment]
By the way...are you starting deploying in a tomcat or just a java run?

**Comment by jangalinski** [comment]
> By the way...are you starting deploying in a tomcat or just a java run?

I just click „run as java application“ on the Application class inside the IDE.

Enjoy your vacation, this can wait!

**Comment by osteinhauer** [comment]
tested with:
- "run as" inside IDE (eclipse)
- `java -jar target/camunda-bpm-spring-boot-starter-example-web-1.1.0-SNAPSHOT.jar`

[http://localhost:8080/rest/engine/default/process-definition](http://localhost:8080/rest/engine/default/process-definition) is reachable (user: _user_, password: _password_).

**Comment by jangalinski** [comment]
yes, thanks for confirming, this was fixed during #22 when we removed resteasy and made a view changes to the Jersey config.
