### ISSUE TITLE
Cannot register service while running unit tests using MockBean

### ISSUE THREAD

**Issue by aeleneski** [camunda/camunda-bpm-spring-boot-starter#208]
This initially stems from this forum posting:

https://forum.camunda.org/t/cannot-register-service-when-running-unit-tests/2755

I was able to come up with an easy test case to re-create the issue that is attached.

There is one @Service (IntService) class with a method that prints to system out and returns an int.

There is one Main class that uses @SpringBootApplication and @EnableProcessApplication.

There are then two test classes, one that Autowires the IntService, and one that creates a MockBean for IntService. 

If you run each test individually, they run successfully.

If you attempt to run both at once, the first runs fine, the second gets an error:

> java.lang.IllegalStateException: Failed to load ApplicationContext
> 
> 	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
> 	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
> 	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:47)
> 	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
> 	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
> 	at org.junit.runners.Suite.runChild(Suite.java:128)
> 	at org.junit.runners.Suite.runChild(Suite.java:27)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
> Caused by: java.lang.RuntimeException: org.camunda.bpm.engine.ProcessEngineException: ENGINE-08043 Exception while performing 'Deployment of Process Application main' => 'Start Process Application Service': Cannot register service org.camunda.bpm.platform.job-executor.process-application:type=main with MBeans Container, service with same name already registered.

[testmock.tar.gz](https://github.com/camunda/camunda-bpm-spring-boot-starter/files/772239/testmock.tar.gz)

**Comment by jangalinski** [comment]
Thanks for reporting .. this looks really strange, I am checking it right now.

**Comment by jangalinski** [comment]
Hi. I confirm this issue. I integrated it in the starter tests, see the commit. So far both tests are ignored.

It seems to  only happen when working with the new spring boot 1.4 MockBean ... if i change the test to also use Autowired, everything is fine. I will mark this as a Bug.

**Comment by aeleneski** [comment]
Yes, I also noticed that as well for switching both tests to use Autowired.

If you need anything else, let me know.

**Comment by osteinhauer** [comment]
Within your tests you are trying to register multiple beans within the same application context. This is wrong usage of spring (testing). This is **not** related to the extension. 

Hints:

1) use different contexts/configurations (one to use ``@Autowired private IntService intService;`` and one to use ``@MockBean private IntService intService;``).

or

2) dirty the context, for example:

```java
@RunWith(SpringRunner.class)
@SpringBootTest
@DirtiesContext
public class IntServiceMockTest {

  @MockBean
  private IntService intService;
...
```
