### ISSUE TITLE
easy and clean support for camunda REST api via starter

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#21]
The current starter supports adding the REST API controllers. The setup is very complicated, there are a lot of dependencies I have to add to my pom to activate this and even then it is not perfectly clear how it all works together and how I can configure it. (see also #20)

Maybe we can find a simpler way by offering a dedicated "starter-rest" that bundles the usual dependencies to run server+api?

Also we should investigate if we can get rid of the jboss/resteasy dependency, doesn't seem to be very "springy" in my opinion ...

**Comment by hawky-4s-** [comment]
Forgot: Also provide a simple spring-boot pom which brings the necessary
dependencies. +1

**Comment by osteinhauer** [comment]
Indeed the dependencies are not really clean. I like the "starter-rest" idea.



> Am 09.09.2015 um 11:30 schrieb Jan Galinski <notifications@github.com>:
> 
> starter-rest

**Comment by jangalinski** [comment]
Christian introduced the starter-rest which makes live easier. But I do not like that the "starter" module has an optional dep on jersey just to provide a RestConfiguration that will be triggered when using the starter-rest module. So I would move the Rest specific stuff to the new module.

**Comment by osteinhauer** [comment]
Move the REST specific stuff to the new module including the `RestConfiguration`class.

**Comment by jangalinski** [comment]
I moved all the code and tests and double checked: works!

Question: do we still need the RestConfiguration class? Or is it enough to provide the Camunda JerseyConfig, so the implementing apps can extend it?
