### ISSUE TITLE
Investigate compatibility with 7.7 release

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-spring-boot-starter#211]
I just did a quick smoke test and had severe problems with the starter and 7.7. Further investigation needed

**Comment by jangalinski** [comment]
Never tried it so far. could you add your stacktraces, so we have a reference to check against in may?

**Comment by berndruecker** [comment]
Two things:

1.) Translation did not work any more, had I18N keys all over the place
2.) Could not log in, had a warning on the console (sorry, long gone).

**Comment by jangalinski** [comment]
we switched to 7.7.0 with #254, I did not experience the issues you mentioned, so I will close for now. Could you please retest with 2.2.0-SNAPSHOT and file separate bug issues if you find anything?

**Comment by berndruecker** [comment]
Thanks! I will test is asap too and reopen if I encounter concrete issues.
