### ISSUE TITLE
exclude examples from maven deploy

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#212]
Though it is good to have as many examples as possible, I doubt it's really useful to have them as artifacts on maven central.

So my idea is to create a maven profile "examples" that is used to validate the current branch but not active when we build releases. 

Objections?

**Comment by sdorokhova** [comment]
Hi @jangalinski ,
I recently moved the examples to https://github.com/camunda/camunda-bpm-examples .
Then the issue is not relevant any more. Right?
