### ISSUE TITLE
HTML forms cannot be retrieved when a WAR artefact is deployed to a non-root context

### ISSUE THREAD

**Issue by andreasmartin** [camunda/camunda-bpm-spring-boot-starter#213]
If I deploy a camunda spring boot WAR artefact to a tomcat using an (application) context other than root or `/`, then the HTML forms using a form key, such as `embedded:app:forms/xyz.html`, cannot be retrieved. It seems to be that `embedded:app:` does not reflect the current (application) context.

I configured the spring boot application as follows ([my project example](https://github.com/DigiBP/CamundaExamples/tree/master/CamundaQuickstart)):
```java
@SpringBootApplication
@EnableProcessApplication
public class ProcessApplicationServlet extends SpringBootServletInitializer {

  public static void main(String[] args) {
    SpringApplication.run(ProcessApplicationServlet.class, args);
  }

  @Override
  protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
    return application.sources(ProcessApplicationServlet.class);
  }
}
```

**Comment by jangalinski** [comment]
must be related to how we set the PROP_SERVLET_CONTEXT_PATH In https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/starter/src/main/java/org/camunda/bpm/spring/boot/starter/SpringBootProcessApplication.java

**Comment by andreasmartin** [comment]
There is an issue with this annotation `@Value("${server.contextPath:/}")` on line 46 of the file [SpringBootProcessApplication.java](https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/starter/src/main/java/org/camunda/bpm/spring/boot/starter/SpringBootProcessApplication.java). Unfortunately, it always returns `/` regardless if you have configured an (application) context other than root or not.

**Comment by osteinhauer** [comment]
see #240
