### ISSUE TITLE
none of the versions greater than 1.3.0 found on maven repositories

### ISSUE THREAD

**Issue by mpprdev** [camunda/camunda-bpm-spring-boot-starter#214]
So the following as described in [documentation](https://camunda.github.io/camunda-bpm-spring-boot-starter/docs/current/index.html) doesn't work.
```
<dependency>
  <groupId>org.camunda.bpm.extension</groupId>
  <artifactId>camunda-bpm-spring-boot-starter</artifactId>
  <version>2.1.0-SNAPSHOT</version>
</dependency> 
```
See also: [maven repo](https://mvnrepository.com/artifact/org.camunda.bpm.extension/camunda-bpm-spring-boot-starter) - the latest version on maven is still 1.3.0

**Comment by osteinhauer** [comment]
For snapshot versions you have to use the camunda snapshot repository

```
<repository>
  <id>camunda-nexus</id>
  <name>camunda bpm community extensions snapshots</name>
  <url>https://app.camunda.com/nexus/content/repositories/camunda-bpm-community-extensions-snapshots</url>
</repository>
```

Nevertheless, starting 2.0 the group id was changed to `<groupId>org.camunda.bpm.extension.springboot</groupId>` (see #132 and [maven repo)](https://mvnrepository.com/artifact/org.camunda.bpm.extension.springboot/camunda-bpm-spring-boot-starter) but the documentation still points to the old id. Thanks for the hint.

**Comment by jangalinski** [comment]
I guess this is fixed with olivers comment ....
