### ISSUE TITLE
provide example with static web resources/customized cockpit

### ISSUE THREAD

**Issue by lldata** [camunda/camunda-bpm-spring-boot-starter#217]
With a plain Spring Boot application with the spring-starter-web dependency I can add a html file to /src/main/resources/static/test.html and access it on localhost:8080/test.html

When I use the Camunda starter this stops working and I get a 404.

Simple example with added static resource:
[example-simple.zip](https://github.com/camunda/camunda-bpm-spring-boot-starter/files/841534/example-simple.zip)

Related to:
https://forum.camunda.org/t/spring-boot-and-static-resources/3065

**Comment by jangalinski** [comment]
thanks for reporting, I can confirm the behavior. Will mark as "bug".

**Comment by lldata** [comment]
What I was really trying to do was to customize the tasklist.
Got any workarounds for that?

**Comment by osteinhauer** [comment]
Taken from the provided example:

```java
...
@EnableWebMvc
public class SimpleApplication implements CommandLineRunner {
...
}
```

Regarding the example: With ``@EnableWebMvc`` [Spring MVC auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-auto-configuration) is disabled and no static content will be served.

Please consider to remove the annotation or you have to configure mvc as described in spring boot docs.

**Comment by falko** [comment]
Is there a chance to release milestone 2.2.0 without this, so that users can start to work with Camunda 7.7?

**Comment by sdorokhova** [comment]
I've just checked. On current v. 2.3.0-alpha1, static resources work fine for me. I'm not using `@EnableWebMvc` annotation.
Example: 
[example-webapp.zip](https://github.com/camunda/camunda-bpm-spring-boot-starter/files/1359771/example-webapp.zip)

Closing the issue. Feel free to open the new issue in [Jira](https://app.camunda.com/jira/browse/CAM), in case I missed smth.
