### ISSUE TITLE
mail properties file not loading

### ISSUE THREAD

**Issue by subbugit** [camunda/camunda-bpm-spring-boot-starter#221]
Hi Camunda Team,
The mail properties configuration with respect classpath given in the https://github.com/camunda/camunda-bpm-mail/blob/master/README.md. 
It was mention that, we can also use classpath:/mail-configuration. 
Would like to know, how we could set this path in a mail project ?

is it in the process.xml file ?

**Comment by subbugit** [comment]
Hi Camunda Team,

When I following the user guide, the mail properties would also be specified using the classpath:/****, but I would like to know how it needs to be configured, is it in process.xml file ?

https://github.com/camunda/camunda-bpm-mail/blob/master/README.md.

Thanks,
Subb

**Comment by jangalinski** [comment]
general questions, especially not related to this extension, are better discussed in the forum: https://forum.camunda.org/c/community-extensions
