### ISSUE TITLE
project structure - separate extension and example

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#23]
With the current setup, examples and implementation share some dependencies and dependencyManagement. This might get confusiing when you try to use the example-app as a template for your own project since it is not clear which dependencies you will need. Also there where mismatches between runtime behavior of ITests and SE when additional dependencies in Test scope triggered some "spring magic".

Suggested fix:
See https://github.com/camunda/camunda-bpm-dropwizard:

on top level the pom.xml will just reference two modules:

* extension - the actual production code
* examples - the example projects

It is ok to define some properties like camunda.version and encoding on this level, but no dependency management and so on.

The extension module will hold the starter projects. These may share common dependencies in the extension/pom.xml

The examples should use a plain spring-boot setup without any camunda-specific parent pom, so they have a clean classpath and only get what is defined in their poms. Examples should not share common dependencies (s.o.) so they can be used as a template for projects.

**Comment by osteinhauer** [comment]
good job
