### ISSUE TITLE
release 2.1.1 fix

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#237]
Sorry to bother you again, @hawky-4s- , but @stefanzilske fixed the dependencies for the gradle module and I think it's a good idea to release a hotfix while there are no new features on master instead of waiting for the 2.2

So

release version: 2.1.1
new (and old) dev version: 2.2.0

Thank you!

**Comment by hawky-4s-** [comment]
Released.
