### ISSUE TITLE
Slack Community for Camunda

### ISSUE THREAD

**Issue by rishirajgarg** [camunda/camunda-bpm-spring-boot-starter#239]
Dear Moderator, 

It would be nice if we can have a slack community to share our thoughts /feedback and communicate with each other about the issue and queries which camunda users or developer may have while using the product. Please advise if there is already any slack community available.

Thanks,

RIshi

**Comment by jangalinski** [comment]
We have our own sub-forum https://forum.camunda.org/c/community-extensions/spring-boot-starter in the official camunda forum.
There is no slack and I am not interested in having one.

**Comment by DevWay1617** [comment]
Hi every one ,
I saw this video:  https://www.youtube.com/watch?v=2OpO-PJVEZs  of Mr Bernd Rücker,
I need the projet but I don't find it , Who can help me please

**Comment by felix-mueller** [comment]
@DevWay1617 
Wow, this is a pretty old video. 
You might want to check this one instead: https://camunda.com/learn/videos/
