### ISSUE TITLE
idGenerator does not apply

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#241]
setting id-generator to strong still leads to dbGenerator

see #224 

reproduce: use example-simple, set camunda.bpm.idGenerator = strong. Expected: ids are strong uuids. But: ids are still simple numeric.

I already did an assert on camundaBpmProperties .. the property value is correct. Also see the tests for idGenerator in the starter module.

**Comment by osteinhauer** [comment]
can you give a more detailed description so I can reproduce?

**Comment by osteinhauer** [comment]
With #244 and after adding ``id-generator: strong`` the logs tell:

```
started instance: dbef917e-2e3e-11e7-bb38-9a907e785252
completed task: Task[dbf18d51-2e3e-11e7-bb38-9a907e785252]
```

can be closed?

**Comment by jangalinski** [comment]
super cool!
