### ISSUE TITLE
Documention link are not working

### ISSUE THREAD

**Issue by deepakshrma** [camunda/camunda-bpm-spring-boot-starter#249]
The updated documentation links are broken. It shows **_Unresolved directive in .._.** error.

[https://camunda.github.io/camunda-bpm-spring-boot-starter/](https://camunda.github.io/camunda-bpm-spring-boot-starter/)

example:
[https://camunda.github.io/camunda-bpm-spring-boot-starter/docs/current/index.html](https://camunda.github.io/camunda-bpm-spring-boot-starter/docs/current/index.html)

**Comment by hawky-4s-** [comment]
Documentation is broken since 28f7e50d3d6c4408c5c2b3271767790d6f2e6fa3

**Comment by jangalinski** [comment]
Do you know if this is because of

a) filenames beginning with number are illegal
b) the relative path changelog/index.adoc -> index.adoc -> 212.adoc is broken?

**Comment by deepakshrma** [comment]
Hi Guys,
Is there any alternative link for these tutorials? I am looking for something, where on spring rest API calls, I can run any process or task with data. Instead of too much conversion of data.

**Comment by jangalinski** [comment]
The 2.0.0 documentation still works https://camunda.github.io/camunda-bpm-spring-boot-starter/docs/2.0.0/index.html

and of Cours you can always check the doc files directly https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/master/docs/src/main/asciidoc

**Comment by jangalinski** [comment]
I worked on the includes, so at least maven clean generate does not fail or warn anymore ... how to apply these changes? Do I have to run publish-docs? Not really sure what to do ... can you help, @hawky-4s- ?

**Comment by osteinhauer** [comment]
any news @hawky-4s- ?

**Comment by hawky-4s-** [comment]
I will check today
