### ISSUE TITLE
example-cloud pom.xml

### ISSUE THREAD

**Issue by forguta** [camunda/camunda-bpm-spring-boot-starter#250]
The project org.camunda.bpm.extension.springboot.example:camunda-bpm-spring-boot-starter-example-cloud:2.2.0-SNAPSHOT (C:\Users\...\Desktop\example-cloud\pom.xml) has 1 error
    Non-resolvable parent POM: Could not find artifact org.camunda.bpm.extension.springboot.project:camunda-bpm-spring-boot-starter-example-root:pom:2.2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]

i can't build with dependency.

**Comment by jangalinski** [comment]
just tried with a fresh git clone ... works. And since also Jenkins and travis are green, this must be a local problem of yours. Try to delete everything you have under .m2/repo/org/camunda/bpm/extension/springboot and run man clean install again.
