### ISSUE TITLE
Cannot disable tenant check when authorization is enabled

### ISSUE THREAD

**Issue by tomorrow10** [camunda/camunda-bpm-spring-boot-starter#252]
Camunda spring boot extensions only allows for authorization configuration following properties

```
public class AuthorizationProperty {

  /**
   * enables authorization
   */
  private boolean enabled = Defaults.INSTANCE.isAuthorizationEnabled();

  /**
   * enables authorization for custom code
   */
  private boolean enabledForCustomCode = Defaults.INSTANCE.isAuthorizationEnabledForCustomCode();

  private String authorizationCheckRevokes = Defaults.INSTANCE.getAuthorizationCheckRevokes();
}
```
It would be useful also to have the possibility to disable tentant check. In standart camunda process engine configuration, there is property for that.
```
  /**
   * If the value of this flag is set <code>true</code> then the process engine
   * performs tenant checks to ensure that an authenticated user can only access
   * data that belongs to one of his tenants.
   */
  protected boolean tenantCheckEnabled = true;

```
Fortunately, there is workaround to set the property via custom configuration but it's a little bit clumsy. It would be cleaner if one could do it via application.yml configuration.

**Comment by jangalinski** [comment]
I just checked, seems we forgot to document a feature: you can use the prefix "camunda.bpm.generic-properties" to configure any property the processEngineConfiguration supports.

In your case:

```
camunda:
  bpm:
    generic-properties:
      tenant-check-enabled: true
```

That being said: I still think that your suggestion is a useful default, so I will mark this issue as "enhancement" and see that we get this supported.

**Comment by tomorrow10** [comment]
Hi thank you for the response, unfortunately, we're currently using 2.0.0 and that generic-properties is probaly in version 2.1.0 I guess. However, good to know.
