### ISSUE TITLE
Provide @ConditionalOnProperty to disable Camunda Auto Configuration

### ISSUE THREAD

**Issue by httpdigest** [camunda/camunda-bpm-spring-boot-starter#259]
There seems to be a good habit for auto configurations to be conditional on a property which allows very easily to disable that auto-configuration. One example is the auto configuration of [Liquibase](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L63), [Flyway](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java#L72) or [Spring Mail](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mail/JndiSessionConfiguration.java#L38).

I know of the other ways for disabling a Spring Boot auto configuration, such as the "exclude" attribute on `@EnableAutoConfiguration` or the `spring.autoconfigure.exclude` property. This, however, is especially painful when writing integration tests (because of how Spring scans for `@EnableAutoConfiguration` annotations on the classpath ancestor classes of the test to detect the main application, and other issues) and it requires the naming of the explicit auto configuration class literal or its name.

Since the boot up of Camunda takes quite a while in integration tests that otherwise don't need the process engine, it'd be very great to have Camunda's Auto Configuration class be conditional on a property, such as `camunda.enabled`, since specifying that property on a test class (via `@TestPropertySource`) is much easier than providing a working application configuration class.

Thanks!

**Comment by jangalinski** [comment]
Sounds like a great idea, I am on it!
