### ISSUE TITLE
BPMN in different containers spring boot

### ISSUE THREAD

**Issue by thiagokuch** [camunda/camunda-bpm-spring-boot-starter#267]
I have two BPMN processes that are in different containers of spring boot. I call my second bpmn from the first and I have a java class problem not being found. I have some way to work with processes in different java containers?

**Comment by osteinhauer** [comment]
Can you provide an example?

**Comment by thiagokuch** [comment]
I have this process called Test1 starting in a spring boot project and calling my process Test2.
![image](https://user-images.githubusercontent.com/6617478/27803706-438264c2-6001-11e7-9ebf-707bf4054ddd.png)
And i have this process called Test2.
![image](https://user-images.githubusercontent.com/6617478/27803756-83832f0c-6001-11e7-95db-a4ccf53a2d15.png)
The two are started on separate spring boot projects and with the same postgres base configured for both. As you can see in figure 1, the Test1 process calls the Test2 process that fails because it does not have access to the JAVA binaries (Test2Delegate).
![image](https://user-images.githubusercontent.com/6617478/27803866-1405503c-6002-11e7-8ff0-898979a6bfcd.png).
My question is if I can have processes in projects with separate spring boot and with their binaries being called between each other.

**Comment by jangalinski** [comment]
Glad you already found the forum ... that is the right place to discuss this since it is not related to the spring boot starter, it's normal camunda behavior.
