### ISSUE TITLE
How to add plugins into ProcessEngineConfiguration

### ISSUE THREAD

**Issue by yf** [camunda/camunda-bpm-spring-boot-starter#269]
Normally, I would do something like that: make a file camunda.cfg.xml with following content:

```
> <?xml version="1.0" encoding="UTF-8"?>
> <beans xmlns="http://www.springframework.org/schema/beans" 
>        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>        xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
> 
>   <bean id="processEngineConfiguration" class="org.camunda.bpm.engine.impl.cfg.StandaloneInMemProcessEngineConfiguration">
>    <property name="processEnginePlugins">
>      <list>
>        <bean class="xxx.yyyy.bpm.parselistener.InformAssigneeParseListenerPlugin" />
>      </list>
>    </property>
>   </bean>
> </beans>
> 
```

How to add plugins into configuration in case of camunda-bpm-spring-boot?
Thanks

**Comment by hawky-4s-** [comment]
Hi, 
have a look at the [documentation](https://camunda.github.io/camunda-bpm-spring-boot-starter/docs/2.1.2/index.html#_adding_additional_configurations). 
There is an example for a process engine plugin.

**Comment by jangalinski** [comment]
Also, please respect the contribution-guidelines: questions in the forum, only bugs/features on github. 

https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/.github/CONTRIBUTING.md

**Comment by abhishu17** [comment]
> Normally, I would do something like that: make a file camunda.cfg.xml with following content:
> 
> ```
> > <?xml version="1.0" encoding="UTF-8"?>
> > <beans xmlns="http://www.springframework.org/schema/beans" 
> >        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> >        xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
> > 
> >   <bean id="processEngineConfiguration" class="org.camunda.bpm.engine.impl.cfg.StandaloneInMemProcessEngineConfiguration">
> >    <property name="processEnginePlugins">
> >      <list>
> >        <bean class="xxx.yyyy.bpm.parselistener.InformAssigneeParseListenerPlugin" />
> >      </list>
> >    </property>
> >   </bean>
> > </beans>
> > 
> ```
> How to add plugins into configuration in case of camunda-bpm-spring-boot?
> Thanks

Hey... can you pls help with some code snipped to add plugin in spring-boot application.

**Comment by sdorokhova** [comment]
Hi @abhishu17 ,
from what I remember you just need to declare a Spring bean implementing `ProcessEnginePlugin` and it will be automatically registered in the engine.

**Comment by jangalinski** [comment]
that is correct
