### ISSUE TITLE
Schema in org.camunda.bpm.spring.boot.starter.configuration.impl.EnterLicenseKeyConfiguration

### ISSUE THREAD

**Issue by aleskurlovich** [camunda/camunda-bpm-spring-boot-starter#272]
It always works with default schema. It will be really usefull to us if you add supporting of camunda.bpm.database.table-prefix.

**Comment by jangalinski** [comment]
Yes, I see ... missed that.

**Comment by cpiepel** [comment]
@jangalinski found this ticket after implementation of my pullrequest. have a look on it on  #273

**Comment by jangalinski** [comment]
Already saw that, will have a look into it, thanks!
