### ISSUE TITLE
Spring Boot and Jbehave

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/camunda-bpm-spring-boot-starter#279]
We want to combine camunda-bpm-spring-boot-startet-test with BDD (camunda-bpm-jbehave).

Running a BDD test fails with 

org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: ReportsCount[stories=2,storiesNotAllowed=0,storiesPending=0,scenarios=2,scenariosFailed=2,scenariosNotAllowed=0,scenariosPending=0,stepsFailed=2]
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:525)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:269)
...

The console shows only 

(java.lang.NoSuchMethodError: org.camunda.bpm.engine.test.assertions.ProcessEngineAssertions.assertThat(Lorg/camunda/bpm/engine/runtime/ProcessInstance;)Lorg/camunda/bpm/engine/test/assertions/ProcessInstanceAssert;)

It seems to be caused by conflicting versions of assertj-core. (1.7.0 to 2.6.0)

What would you change?

Cheers, Ingo

**Comment by jangalinski** [comment]
do you include camunda-bpm-assert manually in the pom?   You shouldn't do that, currently (>2.1) its included in the camunda-bpm-spring-boot-starter-test. See https://camunda.github.io/camunda-bpm-spring-boot-starter/docs/2.2.0/index.html "2. Known issues".

**Comment by ingorichtsmeier** [comment]
Would you suggest to upgrade camunda-bpm-needle to camunda-bpm-assert:2.0-alpha2?

**Comment by jangalinski** [comment]
you should exclude assert from camunda-needle ...

**Comment by jangalinski** [comment]
and ... if you use spring anyway, you should not have to use needle at all ... there must be (didn't use it for a while) jbehave-spring support.

**Comment by sdorokhova** [comment]
Hi @ingorichtsmeier , is this issue still relevant? I'm in the process of moving all issues from here to Camunda Jira. Do you think it's worth creating CAM ticket for this issue?

**Comment by ingorichtsmeier** [comment]
Hi @sdorokhova, the inclusion of the assert library is a bit annoying. If we can clarify this, it would be fine.

**Comment by sdorokhova** [comment]
Have you tried the proposal from @jangalinski ?
> you should exclude assert from camunda-needle ...

**Comment by ingorichtsmeier** [comment]
Yes, it worked in our case.

**Comment by jangalinski** [comment]
I think the assert Extension needs a facelift, there are multiple issues already open to support Java 8, but let’s close it here because it’s not related directly to spring boot
