### ISSUE TITLE
switch to spring-boot 1.3

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#28]
Here are the release note: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes

Imo this is something we should use from now on.

**Comment by osteinhauer** [comment]
Indeed.

Should not impact the configurer itself but the examples. Right?

**Comment by jangalinski** [comment]
Not sure yet.  I gueds you are right,  bur it cones with spring 4.2 and bew security.  We have evaluate if there are new features we want to use and if it's worth sacrificing backward compatibility.

**Comment by jangalinski** [comment]
Sorry  for the last post.  Mobile phone auto "correction" struck

**Comment by osteinhauer** [comment]
I don't see any features we could use for auto configuration. Every project can define the spring boot version by itself by adding the spring boot parent.
