### ISSUE TITLE
org.springframework.transaction.CannotCreateTransactionException: in spring boot camunda

### ISSUE THREAD

**Issue by mbalaas** [camunda/camunda-bpm-spring-boot-starter#280]
Exception while starting ProcessInstanceByKey

**_org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLNonTransientConnectionException: (conn:7057) Connection is close_**

Please note that the above exception raised after 8 or 10 hours deploying application.

**Comment by jangalinski** [comment]
Please provide more context ... (code, pom, db setup) ... this generally works.

**Comment by hawky-4s-** [comment]
This looks like https://stackoverflow.com/questions/31221877/connection-lost-overnight-spring-boot-mysql where the user has to configure connection handling correctly for the datasource.

**Comment by sdorokhova** [comment]
Closing, as there is not enough information. 
@mbalaas , you can ask the question on [forum](https://forum.camunda.org/c/community-extensions/spring-boot-starter) or create the issues in [JIRA](https://app.camunda.com/jira/browse/CAM) where Spring Boot Starter issues are being tracked from now on.
