### ISSUE TITLE
Make AuthenticationFilter registration configurable

### ISSUE THREAD

**Issue by tsabirgaliev** [camunda/camunda-bpm-spring-boot-starter#282]
The following line hardcodes the `AuthenticationFilter` to authenticate requests:

https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/94390d1048980fae925a23277ea9b71cd18ebee2/extension/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java#L63

This could be configurable, so that we can replace the filter with a custom implementation (e.g. for Keycloak integration)

**Comment by sdorokhova** [comment]
Copied to https://app.camunda.com/jira/browse/CAM-8288
Please continue discussion in Jira.
