### ISSUE TITLE
Script Task log output

### ISSUE THREAD

**Issue by icyerasor** [camunda/camunda-bpm-spring-boot-starter#283]
When using a script task that has an inline script like this
`println "Test"`
the output does work fine in a standalone camunda deployment (written to STDOUT/console of tomcat for example). When I deploy the same process to a spring-boot-starter camunda engine, the output seems to get swallowed.

I already tried configuring the log / logback.xml and increase the loglevel, but to no avail.
Not sure if this is a spring-boot or camunda-bpm-spring-boot-starter issue though.

**Comment by sdorokhova** [comment]
Copied to https://app.camunda.com/jira/browse/CAM-8287
Please continue discussion in Jira.
