### ISSUE TITLE
Readme Examples link leads to 404

### ISSUE THREAD

**Issue by abinet** [camunda/camunda-bpm-spring-boot-starter#286]
In readme referenced examples link (https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/master/examples) is not accessible

**Comment by sdorokhova** [comment]
Hi @abinet ,
thank you for pointing out. We're currently in process of reorganizing the project structure. Examples for the version 2.2.0 can be found here: https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/2.2.0/examples

I will fix the link soon.

**Comment by sdorokhova** [comment]
Fixed in https://github.com/camunda/camunda-bpm-spring-boot-starter/commit/818fba17107d4d06d75c6cc5aee4ca1c40d57b5c
