### ISSUE TITLE
Gradle examples have been removed?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-bpm-spring-boot-starter#297]
Gradle examples are no longer supported?

**Comment by sdorokhova** [comment]
Hi Stephen,
we decided not to migrate them, when preparing version 2.3.0.
You can still find the old example [here](https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/2.2.0/examples/example-webapp-gradle)
Feel free to propose a pull request for [Camunda BPM Examples](https://github.com/camunda/camunda-bpm-examples/tree/master/spring-boot-starter) repository 😉 
Best regards,
Svetlana

**Comment by StephenOTT** [comment]
@sdorokhova thanks
