### ISSUE TITLE
Pattern for multiple "process applications"?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-bpm-spring-boot-starter#303]
What is the typical pattern for multiple "process applications" in camunda spring boot?
Example:
You have your overall spring boot which is your single Jar.
But if you are deploying other BPMN processes, supporting delegates, etc, what is the expected structure?

My understanding would be that you would have a shared DB, but each sprint boot application deployment would be "deploymentAware = false" and only grab Jobs for BPMN instances that the specific spring boot instance has definitions for? (deployments being classpath based).

Thanks!

**Comment by Gomzee18** [comment]
@stephenOTT what’s the outcome for this: But if you are deploying other BPMN processes, supporting delegates, etc, what is the expected structure?

**Comment by StephenOTT** [comment]
@StephenOTT the pattern was to create multiple instances of your application.  Each Engine/Process App is a instance of the springboot app
