### ISSUE TITLE
Spring Boot 2.1.0.RELEASE not supported! required a bean of type 'org.camunda.bpm.engine.ProcessEngine' that could not be found

### ISSUE THREAD

**Issue by cbgr** [camunda/camunda-bpm-spring-boot-starter#305]
In project with Spring Boot 2.1.0.RELEASE and camunda-bpm-spring-boot-starter (3.0.0 or last 3.1.0-alpha) error by deploy
Description:

Field processEngine in org.camunda.bpm.engine.spring.SpringProcessEngineServicesConfiguration required a bean of type 'org.camunda.bpm.engine.ProcessEngine' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

This is because in CamundaBpmAutoConfiguration imported SpringProcessEngineServicesConfiguration.
In  SpringProcessEngineServicesConfiguration autowired ProcessEngine bean, BUT ProcessEngine bean  declared in CamundaBpmAutoConfiguration. And ProcessEngine bean is not created at the time of SpringProcessEngineServicesConfiguration processing.

**Comment by cbgr** [comment]
Hi @tasso94, 

thanks for workaround!
But due to the specifics of our project, we cannot change the Spring Boot version.

You can tell when you plan to add support Spring Boot 2.1 in Camunda BPM Spring Boot Starter?

**Comment by tasso94** [comment]
Hi @cbgr,

unfortunately support for Spring Boot 2.1 hasn't been scheduled yet. 

There are two ways to speed things up:
* Either you could contribute to this repository by providing a pull request
* Or, in case you are a Camunda customer, feel free to raise a support ticket

Cheers,
Tassilo

**Comment by SayakMukhopadhyay** [comment]
Does this mean that Camunda does not support Java 11? Java 9 and 10 have both reached the end of life for supports and is not suited for production environments. I say this cause Java 11 support arrived for Spring Boot at 2.1.0. 
I see that the latest starter supports Camunda 7.9 and support for Java 11 was added in Camunda 7.10.
It would be great if the starter could be moved to Camunda 7.10 and Spring Boot 2.1.0 to provide Java 11 support.

**Comment by meyerdan** [comment]
The following issue currently blocks us from making progress: spring-projects/spring-boot#15175

See also: https://app.camunda.com/jira/browse/CAM-9466

As soon as a fix is released we will making support for spring boot 2.1.0 a priority. There will then be a release of the camunda spring boot starter targeting both Camunda 7.10 and Spring boot 2.1.x

Does this help you?

**Comment by SayakMukhopadhyay** [comment]
Thanks @meyerdan ! That explains everything.  Looking forward to Spring Boot 2.1.1 getting released then.

**Comment by yanavasileva** [comment]
As Daniel mentioned feel free to track the status of https://app.camunda.com/jira/browse/CAM-9466
Hereby I am closing the issue.
In case of further questions feel free to post in the [forum](https://forum.camunda.org/) or create a [jira ticket](https://app.camunda.com/jira/secure/CreateIssue!default.jspa).

**Comment by meyerdan** [comment]
FYI: Support for Spring Boot 2.1.1 has now been released: https://blog.camunda.com/post/2018/12/camunda-spring-boot-starter-320-released/
