### ISSUE TITLE
"invalid date value "+propertyValue

### ISSUE THREAD

**Issue by 18506711722** [camunda/camunda-bpm-spring-boot-starter#309]
org.camunda.bpm.engine.impl.form.type.DateFormType
deprecated method  convertFormValueToModelValue  Still being used  Date tyepe to String type lead to 'invalid date value'

`if(defaultValue != null) {
        formField.setDefaultValue(type.convertFormValueToModelValue(defaultValue));
      } else {
        formField.setDefaultValue(null);
      }`

**Comment by jangalinski** [comment]
Please open new issues here: https://app.camunda.com/jira/browse/CAM
