### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by hawky-4s-** [camunda/camunda-bpm-spring-boot-starter#31]
Hi @jangalinski, @osteinhauer,

What would you like to integrate into the 1.1.0 Release? I want to cut it and start working on the remaining issues.

Cheers,
Christian

**Comment by meyerdan** [comment]
There are already 30 commis on master since last release.
Why not release it right away?
Do you need more stuff?

:hamburger:

**Comment by jangalinski** [comment]
webjar camunda webapp starter did not work when I tested it ... this schould be part of the release. Can anyone confirm/retest?

**Comment by meyerdan** [comment]
Can't you release the current status and then do another relase with only the webjar thing?

**Comment by jangalinski** [comment]
We could ... but why should we release with a "closed" issue that does not work? Can you just run the webapp example on your machine and see how it goes?

**Comment by meyerdan** [comment]
Sounds like that issue needs re-opening :=)

Idea 1:
- re-open webjar issue
- move webjar stuff to branch
- release project.
- then fix webjar stuff

Idea 2:
- just release it and declare the webjar stuff as "experimental" or "known issue".

You are probably thinking: "why is that guy trolling here in the spring boot project? Doesn't he have other things to do? Doesn't he have his own releases to cut?"

The answer is: Yes I do. However, I know the desire of putting that last feature / bugfix ... into the release and while I am doing that discovering new things to put the next thing in there as well and by this putting off the release again and again and in the end never releasing anything. Knowing this so well I can maybe help somewhere else when I think I see similar tendencies. But feel free to completely ignore / mute me :=)

**Comment by osteinhauer** [comment]
By the way issue #3 is still open. Anyway there must be someone who tests and create issues. Without I have no idea what is not working.

Nevertheless I can follow Daniel: There can be a release without the web starter.

**Comment by hawky-4s-** [comment]
I will test #3 and put some work into the project tomorrow or monday as slacktime to fix any remaining issues.
Can we agree on a release date next week?

**Comment by osteinhauer** [comment]
I agree with a release independent if #3 is integrated or not.

**Comment by nikku** [comment]
I am a fan of releasing early and often. #3 looks like a nice candiate for a follow up release. :cactus:

**Comment by lofidewanto** [comment]
I tried the webjar stuff:

1. I can open the 3 webapps: tasklist, cockpit and admin.
2. I have to insert a new user for Camunda as usual and this works just fine.
3. Problem: with the new created user I cannot login into the webapp. This looks like the problem of the "standard" H2 DB in memory.

I will try to use other DB and try to restart the Spring Boot service.

**Comment by jangalinski** [comment]
What is the url you use to access the webapp?

**Comment by osteinhauer** [comment]
Are you running the example [Applikation](https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/examples/camunda-spring-boot-starter-example-webapp/src/main/java/org/camunda/bpm/spring/boot/starter/example/webapp/Application.java)? If so, there should be no context in the URL and the frontend should be accessible using http://localhost:8080/

**Comment by lofidewanto** [comment]
OK it works, I also try with our own process model project. The problem was the Spring Security. If you have the jar in your classpath you need to turn it off:

security.basic.enabled=false

or just exclude the spring-security.jar.

I can use all three webapps without any problem.

Thanks,
Lofi

**Comment by jangalinski** [comment]
Yes, I run the example-webapp Application. I get a 404 when I open http://localhost:8080/

**Comment by lofidewanto** [comment]
Try this address:
localhost:8080/"context"/app/cockpit/index.html

Or just without "context".

**Comment by jangalinski** [comment]
This localhost:8080//app/cockpit/index.html works for me.

I would have expected localhost:8080/camunda (or localhost:8080/ as oliver suggested). Do we need to set an acceptance criteria on the issue ("should be reachable under ....")? I find it rather unintuitive to guess link contents ....

But still: it works ... so I am with you for the 1.1.0 release :+1:

**Comment by osteinhauer** [comment]
I expected that the webapp is reachable under `/`. It worked for me but I was blended by browser cache - sorry for that.

I fixed this with commit 897dc0bea892f5d0efa9b364cdb6f92257dfc760 and added some docu with commit 90b15619e630d8d41376d8e5c733faf8dfb924dd.

**Comment by meyerdan** [comment]
Still no release :crying_cat_face:

**Comment by jangalinski** [comment]
Sorry, I checked that the cockpit is accessible with the latest fix from Oliver but then discovered that the tasklist is not usable because filters do not work because of the json-header bug Daniel found.

We can release though, just have to accept missing tasklist as known bug. Christian?

**Comment by meyerdan** [comment]
Lets make deal :-Dollar:

1. You do a release of Spring Boot
2. I will fix the tasklist header bug :)
3. You do another release of Spring Boot

This way we have two releases : Zap:

**Comment by jangalinski** [comment]
And we all know: 2 releases are better than 1 release. At least twice as good, I'd say :-)

**Comment by meyerdan** [comment]
awesomeness =  2^(Number of releases)

**Comment by osteinhauer** [comment]
please please do the release

...sounds like a song :)

**Comment by nikku** [comment]
Be noisy guys. More releases, more publicity, more fame and fortune for camunda-bpm-spring-boot-starter.

**Comment by osteinhauer** [comment]
🍪

**Comment by meyerdan** [comment]
:crying_cat_face: :crying_cat_face: :crying_cat_face:

**Comment by nikku** [comment]
:+1: for release.

**Comment by hawky-4s-** [comment]
Release :beers:  today and :cookie:s on monday for me please -> [1.1.0](https://github.com/camunda/camunda-bpm-spring-boot-starter/releases/tag/1.1.0)

**Comment by meyerdan** [comment]
:joy_cat: :joy_cat: :joy_cat:

**Comment by meyerdan** [comment]
Will there be a blogpost as well?

**Comment by meyerdan** [comment]
Would be really cool if we could produce some kind of blogpost or release notes so that users know that there is a new release and what is in it.
A short announcement, 5 lines of text would be enough...

Let me know if I can help out.
