### ISSUE TITLE
Camunda bpmn with mockbean, not detecting Java class instance

### ISSUE THREAD

**Issue by maheshps-huawei** [camunda/camunda-bpm-spring-boot-starter#312]
I have written bpmn flow. This BPMN just contains Service Task. This service task is implemented by Java Class   ServiceInstantiationFeasibilityReqToSLODelegate.

Below code works fine without mock.

@RunWith(SpringRunner.class)
@SpringBootTest
@ContextConfiguration(locations = "/applicationContext_forNetworkSlicing.xml")
public class InputValidationTest {
  
    @Autowired
    private RuntimeService runtimeService;
     
    @Autowired
    @Rule
    public ProcessEngineRule processEngineRule;
       
    private static MsoLogger LOGGER = MsoLogger.getMsoLogger(MsoLogger.Catalog.GENERAL, HandleUnexpectedError.class);
    
    
    @Test
    @Deployment(resources = {"process/ProcessServiceInstantiationFeasibility.bpmn"})
    public void validateIncomingReq() {
        // given
    	BpmnAwareTests.init(processEngineRule.getProcessEngine());
        Map<String, Object> variables = new HashMap<>();
        variables.put("id","42");
        variables.put("href","http://serverlocation:port/orderManagement/serviceOrder/42");
        
        // when     
        ProcessInstance instance = runtimeService
                .startProcessInstanceByKey("ProcessServiceInstantiationFeasibility", "businessKey", variables);

        // then
        BpmnAwareAssertions.assertThat(instance).isEnded().hasPassedInOrder(
                "StartEvent_Feasibility",
                "ScriptTask_ValidateIncomReq",
                "ServiceTask_call_SLO",
                "ServiceTask_ServInstanceFeasCompletion",
                "EndEvent_Feasibility"
        );        
    }
}

@Component
public class ServiceInstantiationFeasibilityReqToSLODelegate implements JavaDelegate {
    private static MsoLogger LOGGER = MsoLogger.getMsoLogger(MsoLogger.Catalog.GENERAL, ServiceInstantiationFeasibilityReqToSLODelegate.class);
    private static final String LOGMARKER = "[NETWORK-SLICE-FEASIBILITY-CHECK]";
    
  public void prepareServiceInstantiationFeasibility(DelegateExecution execution) {
	  execution.setVariableLocal("statusCode", true);
  }
  
  public void sendRequestToSLO(DelegateExecution execution) {
	  //rest call
  }

  @Override
  public void execute(DelegateExecution execution) throws Exception {
	  LOGGER.info(LOGMARKER + "==ServiceInstantiationFeasibilityReqToSLODelegate==");
	  
	  prepareServiceInstantiationFeasibility(execution);
	  
	  sendRequestToSLO(execution);
  }
}

If I want to mock class ServiceInstantiationFeasibilityReqToSLODelegate as MockServiceInstantiationFeasibilityReqToSLODelegate , I have declared as below:

    @MockBean
    private MockServiceInstantiationFeasibilityReqToSLODelegate serviceInstantiationFeasibilityReqToSLODelegate;

During execution, it is not detecting Java Class instance. Means MockServiceInstantiationFeasibilityReqToSLODelegate .execute(...) is not getting called. Content of ServiceInstantiationFeasibilityReqToSLODelegate and MockServiceInstantiationFeasibilityReqToSLODelegate  are same.

How to fix this??

**Comment by maheshps-huawei** [comment]
![BPMN](https://user-images.githubusercontent.com/12078811/54915912-3f3baf00-4f1e-11e9-8109-5e21391aee54.jpg)

**Comment by maheshps-huawei** [comment]
![BPMN](https://user-images.githubusercontent.com/12078811/54915979-64302200-4f1e-11e9-9a11-18dbe393d356.jpg)

**Comment by maheshps-huawei** [comment]
Now I have modified to add doAnswer() as below:

			doAnswer((i) -> {
				i.callRealMethod();
				return null;
			}).when(serviceInstantiationFeasibilityReqToSLODelegate).execute(any(DelegateExecution.class));
			
			
			
	        ProcessInstance instance = runtimeService
	                .startProcessInstanceByKey("ProcessServiceInstantiationFeasibility", "businessKey", variables);

Now MockServiceInstantiationFeasibilityReqToSLODelegate .execute(...)  is getting called. But whatever set variable "statusCode" is not visible to Gateway.

16:46:54.011 [main] ERROR org.camunda.bpm.engine.context - ENGINE-16004 Exception while closing command context: Unknown property used in expression: #{statusCode}. Cause: Cannot resolve identifier 'statusCode'
org.camunda.bpm.engine.ProcessEngineException: Unknown property used in expression: #{statusCode}. Cause: Cannot resolve identifier 'statusCode'
	at org.camunda.bpm.engine.impl.el.JuelExpression.getValue(JuelExpression.java:60)

Please help me to fix this.

**Comment by maheshps-huawei** [comment]
execute() method is not calling prepareServiceInstantiationFeasibility() in mocking case. Anyone knows why this issue? Without mocking, it calls.

**Comment by yanavasileva** [comment]
Hi @maheshps-huawei ,

Please do not create issues here.
Could you please post this in the forum - https://forum.camunda.org/

**Comment by jangalinski** [comment]
since the only isssue left here is the "auto" history level ... shouldn't we just move/close  it  and disable issues on repo for good?

**Comment by yanavasileva** [comment]
Hi @jangalinski,

I agree. I will take care.
