### ISSUE TITLE
delegate response is slow

### ISSUE THREAD

**Issue by Phosphor-zhl** [camunda/camunda-bpm-spring-boot-starter#313]
Dear Camunda Team:
  I encountered a slow response in the production environment, and I can't analyze the reason. Please help me. Thank you!

<dependency>
	<groupId>org.camunda.bpm</groupId>
	<artifactId>camunda-bom</artifactId>
	<version>7.6.0</version>
	<scope>import</scope>
	<type>pom</type>
</dependency>

1. start workflow
![image](https://user-images.githubusercontent.com/17038799/56672285-c3817d80-66e8-11e9-9a8e-aaf72034ab34.png)

2. start workflow log(15:10)
![image](https://user-images.githubusercontent.com/17038799/56672330-dbf19800-66e8-11e9-99b5-f341f6b9e6a2.png)
![image](https://user-images.githubusercontent.com/17038799/56672359-e7dd5a00-66e8-11e9-9456-a935198cfdf8.png)

3. workflow
![image](https://user-images.githubusercontent.com/17038799/56672390-f297ef00-66e8-11e9-993e-2049f715fed1.png)

4. delegate starts working(15:13), The difference is close to two minutes
![image](https://user-images.githubusercontent.com/17038799/56672458-0ba0a000-66e9-11e9-9c9a-9717d138c7c1.png)

**Comment by osteinhauer** [comment]
nevertheless this may occur on async defined delegate execution. if so you have to configure the job executor for your productional needs.

but PLEASE use jira for now.

**Comment by yanavasileva** [comment]
Related jira ticket: https://app.camunda.com/jira/browse/CAM-10217
