### ISSUE TITLE
Provide links to external examples in README

### ISSUE THREAD

**Issue by hawky-4s-** [camunda/camunda-bpm-spring-boot-starter#32]
Hi @jangalinski , @osteinhauer,

Do you think it would be good to merge @osteinhauer 's  [camunda-spring-boot-starter-examples](https://github.com/osteinhauer/camunda-spring-boot-starter-examples) with the currently existing ones and do some improvements on them?

**Comment by osteinhauer** [comment]
Not sure about that. There should be some examples showing the usage in plain boot projects independent of the camunda starter poms.

**Comment by jangalinski** [comment]
Not sure either  cause I am not familiar with the examples Oliver build before we started this extension. I would think its up to Oliver to decide if there are some left that should be ported.
Imho it would be a good idea to close our private repos so googling users wont get confused with many camunda-spring-boot repos. Or at least change the README so it points to this extension.

**Comment by osteinhauer** [comment]
It is an example repo showing how one can use the starters in an easy way. The [README](https://github.com/osteinhauer/camunda-spring-boot-starter-examples/blob/master/README.md) says: "Examples showing the easy and less code usage of [camunda-bpm-spring-boot-starter](https://github.com/camunda/camunda-bpm-spring-boot-starter)"

**Comment by hawky-4s-** [comment]
I really would like to have that in the project somehow or maybe create an additional repository just for the examples. It is always easier to read the whole stuff in a project as code instead of documenting it.

**Comment by jangalinski** [comment]
I dont think anything will happen here. We could just setup an example README and list external examples instead. ok?

**Comment by hawky-4s-** [comment]
👍

**Comment by hawky-4s-** [comment]
Changed the title to reflect what we agreed on
