### ISSUE TITLE
Publish documentation for different versions

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#33]
By now http://camunda.github.io/camunda-bpm-spring-boot-starter/ is published with the latest snapshot version. So the docus for a release are lost.

It would be much better to have the docs for every release and the latest snapshot like:

http://camunda.github.io/camunda-bpm-spring-boot-starter/snapshot/
http://camunda.github.io/camunda-bpm-spring-boot-starter/1.0.0/
http://camunda.github.io/camunda-bpm-spring-boot-starter/1.1.0/
http://camunda.github.io/camunda-bpm-spring-boot-starter/current -> 1.1.0/

http://camunda.github.io/camunda-bpm-spring-boot-starter/ should contain a table of content like link collection for the different versions.

For an example take a look at http://projects.spring.io/spring-boot/

**Comment by jangalinski** [comment]
:+1: like it.

Additionally, we could use a "release" branch and make this one default on github. So when I enter the github repo page, I do not get confused with the latest snapshhot stuff that goes on on master. (or, if you prefer, master will be used for releases only and we use a new dev branch for snapshot.s

**Comment by osteinhauer** [comment]
any news?

**Comment by hawky-4s-** [comment]
@osteinhauer:
I will tackle this issue this evening

**Comment by hawky-4s-** [comment]
Closed by b14378ac083a3427357609df9088a79a84766835

**Comment by hawky-4s-** [comment]
There is still room for improvement. It is a quick hack using the existing asciidoc template and jquery/handlebars.js. I will add some enhancements.

**Comment by jangalinski** [comment]
Maybe worth a blog post when you are done?
