### ISSUE TITLE
Cannot set databaseSchemaUpdate to create-drop

### ISSUE THREAD

**Issue by pokkie** [camunda/camunda-bpm-spring-boot-starter#38]
In DefaultDatasourceConfiguration line 34:

`configuration.setDatabaseSchemaUpdate(Boolean.toString(camundaBpmProperties.getDatabase().isSchemaUpdate()));`

should rather read: 

`configuration.setDatabaseSchemaUpdate(camundaBpmProperties.getDatabase().isSchemaUpdate());`

and so if you specify create-drop, the application fails to start up

**Comment by jangalinski** [comment]
implemented. Thanks for the hint
