### ISSUE TITLE
Hosted link does not work

### ISSUE THREAD

**Issue by bikkimahato** [camunda/camunda-bpm-spring-boot-starter#435]
![image](https://user-images.githubusercontent.com/42492682/174100273-7e156cea-40d4-4acb-8b62-ca1d4cd8ab0a.png)

**Comment by ThorbenLindhauer** [comment]
Thank you, I removed the link. You can find the docs here: https://docs.camunda.org/manual/develop/user-guide/spring-boot-integration/
