### ISSUE TITLE
Lifecycle events: ProcessApplicationStarted and ProcessApplicationEnded

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#47]
Right now, we are relying on ApplicationListener finishedWithoutError and get Lifecycle interference with CommandLineRunner, ApplicationContextAware, ContextRefreshEvent, ...

I think it is a good idea to introduce custom events for camunda start/stop and encourage users to rely on these events only. Few notes: https://dzone.com/articles/better-application-events

**Comment by osteinhauer** [comment]
Hi Jan, I gave you a start with 5edf30d.

**Comment by jangalinski** [comment]
nice one, thanks.

**Comment by jangalinski** [comment]
merged
