### ISSUE TITLE
apply camunda developer guidelines

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#5]
In the past, we agreed on some rules when it comes to contributions. see http://camunda.org/contribute/

**Rules for Java-based Projects**

> Java-based projects must use Apache Maven as build system. The groupId must start with
> org.camunda.bpm.extension. The artifactId must start with camunda-bpm-*. camunda will supply a 
> maven pom template with sensible default values.

So the question is: do we drop these rules? Otherwise we should rename the repo and project root.

**Comment by hawky-4s-** [comment]
I would either leave the repo as it is or rename it to camunda-bpm-spring-boot-starter.

**Comment by osteinhauer** [comment]
renaming should be fine

Von meinem iPhone gesendet
