### ISSUE TITLE
support 7.4 services - implement ProcessEngineServices

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#51]
I noticed that configuration for newer service api like DecisionService and ExternalTaskService was missing. 
When we implement ProcessEngineServices in CamundaBpmAutoConfiguration, we will notice this on compile time in the future.

**Comment by osteinhauer** [comment]
Doesn't it break compatibility for earlier versions?

**Comment by jangalinski** [comment]
Earlier versions of camunda-bpm-spring-boot? How so? Seeing the autoconfiguration as a "black box", there is still one input "processEngineConfigurationImpl" and n outputs (the service beans).
Breaking only could occur if you manually extended the configuration to mess with the services returned ... and I do not really see a use case where anyone would have done that. Do you?
The benefits of relying on the camunda-api only when it comes to "what api services are provided" are more important, imho.
