### ISSUE TITLE
Spring Initializr?

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-spring-boot-starter#52]
A customer asked me if there are any plans to integrate this into http://start.spring.io/

**Comment by jangalinski** [comment]
I die a quick google but did not find documentation on how to do that.  Any clue?

**Comment by jangalinski** [comment]
I openend https://github.com/spring-io/initializr/issues/218

**Comment by jangalinski** [comment]
I created https://github.com/spring-projects/spring-boot/pull/5790 over at the spring boot 3rd party starters. I think currently this is all we can do ... I will close with an option to re-issue once the camunda starter gets enough reputation to try again to get into the initializr.
