### ISSUE TITLE
Use Deployment utils from platform-engine to find deployable resources

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#53]
I found that the current implementation to discover bpmn and cmmn files implemented in https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/camunda-spring-boot-starter/src/main/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultDeploymentConfiguration.java  does also find packages/directories with that name (org.mydomain.process.bpmn/).  I built a filter to check if the forun resource `!isDirectory`, but this duplicates functionality already implemented in engine.
Also, for the current acm plugin it is required to deploy the cmmn-diagram graphics because there is no js-renderer. This is also already implemented and should be reused.

Conclusion: Do not scan for deployable packages in this starter, re-use utils already present in the engine.

**Comment by hawky-4s-** [comment]
Sounds reasonable.

**Comment by jangalinski** [comment]
Fixed via  #76 
when using the SpringBootProcessApplication and an (empty) META-INF/processes.xml, this is now done via the RuntimeContainer deployment steps like any normal war deployment. If the SpringBootProcessApplication is not used, SpringProcessEngineConfigurations autoDeploy is used.
