### ISSUE TITLE
spring-boot:run and livereloading of web static assets

### ISSUE THREAD

**Issue by fouasnon** [camunda/camunda-bpm-spring-boot-starter#54]
I would like to live-reload my web assets as I change them instead of recompiling at each point.  My project uses this spring boot starter project and the `camunda-bpm-spring-boot-starter-webapp` dependency.  I have some customized assets that overlay the default webapp assets that currently live in `src/main/webapp/*` in my project. 

I was looking into using the `spring-boot-devtools` util to enable live-reloading, but I don't think this plays nicely with mvn overlay paradigm. See this recent issue on the matter:  https://github.com/spring-projects/spring-boot/issues/1030

I would like to know if this project, or perhaps the camunda webapp project, has any plans to move away from the overlay paradigm. Or is there another way to make livereloading work with either the devtools or some other utility that accomplishes the same thing?  Does this project intend to introduce any development tools for developing the webapp further or are there larger changes happening in the webapp project to facilitate frontend development and extension? 

Thanks! Also thanks for all the recent development on this project.  It's been very helpful.

**Comment by fouasnon** [comment]
Btw, when I say "live-reloading", I'm not talking about how-swapping java classes.  I just want to livereload static assets that are being overlayed onto the default webapp.

**Comment by ronalders** [comment]
Hi @fouasnon how did you setup the overlay of the default webjar content did you just serve the static content on the same location of the webjar content?  Do you have a sample project on github.

**Comment by osteinhauer** [comment]
@fouasnon Have you posted your question to camunda webapp project or found any solution?

**Comment by fouasnon** [comment]
I have not posted my issue to the general forum, but forking the 7.5 web app repo seems like a better alternative to the mvn overlay style at the moment.

**Comment by osteinhauer** [comment]
OK. Do you like to provide a small sample project?

**Comment by amitjif** [comment]
I'm facing same issue. I liked camunda-starter-webapp feature but like to customise tasklist in my springboot project without loosing other benefits provided by embedded web app.. But can't really do that.. So, for taking my Camunda application to enterprise level can't really happen by using embedded camunda-*-starter-webapp.. Any thoughts ?
