### ISSUE TITLE
Configuration api: rename "apply" to "accept"

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#56]
We do not use Java 8 so for, but the default functional interface for a void method taking one parameter is the Consumer, which has the signature Consumer#accept(T value). Currently, "apply" is used, which in java8 is an indicator for a Function (O apply(I input)).

This is more readable for users used to Java8 functional interfaces and makes it easier to adopt functional interface once we change the code base to Java8.

Risk: this is a breaking api change, but we can assume that there are not many custom configurations out in the field so far, so better now than later. Alternatively, we could keep a deprecated apply() method that delegates to the accept() for some time.

**Comment by osteinhauer** [comment]
same thing with accept() as it is used in [Consumer](https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html).

Decided to follow "better now than later" and refactored to alter(). So code can be read like `camundaConfiguration.alter(engineConfiguration);`

@jangalinski if you agree please close

**Comment by jangalinski** [comment]
Regarding your remark with "alter": I want this to use the Consumer#accept signature, so the change now is perfect. Thanks.

By the way: I was wandering if we should use ProcessEnginePlugins for these kind of Configuration extensions.
The preInit() method is exactly what we are doing anyway but we would have the chance to still use postInit and postEngineBuild for more complex operations (history level, db setup, ...).

What do you think?

**Comment by osteinhauer** [comment]
Not sure if I am right: The mechanism sounds like a good idea but I would expect that a ProcessEnginePlugin extends the engine and is not responsible for configuration. On the other hand a SpringBootAutoConfigurationPlugin would fit into the patter...

**Comment by jangalinski** [comment]
Most of the plugin usage out there is about modifying configuration, you rarely see postInit or postEngineBuild in use.
I am just thinking of the visitor pattern and see that camunda already has an implementation for it, and we are building the same again (as preInit).

**Comment by osteinhauer** [comment]
created a branch (see commit above) to see how it looks like. I think it is a good idea to use the plugin mechanism. Classes and packages needs to be refactored to finalize...

**Comment by jangalinski** [comment]
I am interested in seeing this. Did you push it? Btw: Lets continue on a new issue: #86
