### ISSUE TITLE
Why do we have CamundaConfiguration and AbstractCamundaConfiguration?

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#57]
I just extended the configuration and wondered why we do have an interface to enforce the apply() method (see #16) and an additional abstract class just to have the properties injected? This seems to be overkill, as we could just define the abstract class, no one (as far as I can see) just implements the interface.

**Comment by osteinhauer** [comment]
The idea behind: anyone using the starter can add own configurations just by implementing the interface and exposing as bean. Internal stuff - camunda properties for now - go into the abstract class and my be changed.

**Comment by jangalinski** [comment]
ok, thanks, sounds like a good idea, I wont touch it.
