### ISSUE TITLE
Document how to use Camunda BPM Enterprise Edition with Spring Boot

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-spring-boot-starter#66]
I tried setting:

```
<properties>
    <camunda.version>7.4.5-ee</camunda.version>
</properties>
```

and using the Camunda BOM:

```
<dependencyManagement>
    <dependency>
      <groupId>org.camunda.bpm</groupId>
      <artifactId>camunda-bom</artifactId>
      <version>${camunda.version}</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
</dependencyManagement>
```

but the app still starts with:

```
Spring-Boot: (v1.3.3.RELEASE)
Camunda BPM: (v7.4.0)
Camunda BPM Spring Boot Starter: (v1.1.0)
```

and Cockpit does not show up with EE features like history and reporting.

**Comment by falko** [comment]
Explicit management of the required artifacts works:

	<dependencyManagement>
		<dependency>
		  <groupId>org.camunda.bpm</groupId>
		  <artifactId>camunda-bom</artifactId>
		  <version>${camunda.version}</version>
		  <scope>import</scope>
		  <type>pom</type>
		</dependency>
		<dependencies>
			<dependency>
				<groupId>org.camunda.bpm</groupId>
				<artifactId>camunda-engine-spring</artifactId>
				<version>${camunda.version}</version>
			</dependency>
			<dependency>
				<groupId>org.camunda.bpm.webapp</groupId>
				<artifactId>camunda-webapp-webjar</artifactId>
				<version>${camunda.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

**Comment by jangalinski** [comment]
I guess this is related to #64 : camunda-bom does not contain the webapp.

Engine Spring should have worked though. But I am already on 1.2.0-SNAPSHOT, so I have to check it. 
It should be possible to rely on the boms (camunda+springboot) without manually tweak the versions.

**Comment by falko** [comment]
@camunda-jenkins: Thank you Jenkins. I knew you could help here! You're right: the Enterprise Edition webapp has the following coordinates:

    <dependency>
      <groupId>org.camunda.bpm.webapp</groupId>
      <artifactId>camunda-webapp-ee-plugins</artifactId>
      <version>7.5.0-SNAPSHOT</version>
      <type>war</type>
      <scope>runtime</scope>
    </dependency>

**Comment by falko** [comment]
There is no webjar available from that EE dependency. That's why I reopened this. The EE webjar is in discussion as part of https://app.camunda.com/jira/browse/CAM-5707

**Comment by falko** [comment]
I tried to create an EE webjar and attached the pom.xml to: https://app.camunda.com/jira/browse/CAM-5707

It can be integrated in an application using the Spring Boot Starter like this:

	<dependencies>
			<dependency>
			  <groupId>org.camunda.bpm.webapp</groupId>
			  <artifactId>camunda-webapp-ee-webjar</artifactId>
			  <version>${camunda.version}</version>
			</dependency>	
    <dependency>
      <groupId>org.camunda.bpm.extension</groupId>
      <artifactId>camunda-bpm-spring-boot-starter-webapp</artifactId>
      <version>1.1.0</version>
      <exclusions>
      	<exclusion>
      		<artifactId>camunda-webapp-webjar</artifactId>
      		<groupId>org.camunda.bpm.webapp</groupId>
      	</exclusion>
      </exclusions>
    </dependency>

However, the history features do still not show up in Cockpit.

**Comment by PG2000** [comment]
Do you know any Workaround for this until the ee jar is available ?

**Comment by falko** [comment]
Issue https://app.camunda.com/jira/browse/CAM-5707 was closed. But the feature request for an EE jar is still open: https://app.camunda.com/jira/browse/CAM-5834

If you're an EE customer, contact Camunda support about this.

**Comment by jangalinski** [comment]
I renamed this because with @berndruecker s [consulting example](https://github.com/camunda/camunda-consulting/tree/master/snippets/camunda-webapp-webjar-ee)  we have a workaround that allows using ee-webapp.
Its probably a good idea anyway to not use the "one" webjar available but instead provide a custom builder that allows additional plugins, or hiding certain apps (admin, tasklist, ...)
