### ISSUE TITLE
Camunda Webapp Webjar not available for 7.5

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-spring-boot-starter#67]
The webjar has been deleted by this commit:
https://github.com/camunda/camunda-bpm-webapp/commit/0847ba9f9b09e62018aca19b2287bdfdf7697043

And is no longer available for current alpha versions of Camunda 7.5
https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/webapp/camunda-webapp-webjar/

**Comment by falko** [comment]
related to #64, #63 & #66

**Comment by falko** [comment]
#35 mentions a JIRA issue https://app.camunda.com/jira/browse/CAM-5707

**Comment by falko** [comment]
A pull request is already prepared: https://github.com/camunda/camunda-bpm-platform/pull/223

**Comment by jangalinski** [comment]
Its there again for 7.5.0-alpha4     shttps://app.camunda.com/nexus/service/local/repositories/camunda-bpm/content/org/camunda/bpm/webapp/camunda-webapp-webjar/7.5.0-alpha4/
