### ISSUE TITLE
webapp starter disables standard directories for static resources

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-spring-boot-starter#68]
camunda-bpm-spring-boot-starter-webapp seems to disable the Spring Boot standard directories for static resources as described here: http://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot

Files in src/main/resources/static should be served in the context root of the webapp. With camunda-bpm-spring-boot-starter that works fine. The class [CamundaBpmWebappAutoConfiguration](https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/extension/camunda-spring-boot-starter-webapp/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.java) seems to overwrite this:

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
      registry.addResourceHandler("/**").addResourceLocations("classpath:/");
      super.addResourceHandlers(registry);
    }

**Comment by jangalinski** [comment]
Note: using formKey embedded:/static/forms/my-form.html works
