### ISSUE TITLE
allow springbootprocessapplication to work without processes.xml

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#77]
- [ ] we need a custom Container because we do not want to require a processes.xml. So we need to modify the ParseProcessesXml step -> when no xml is found, properties are used. This could later become part of platform itself
- [ ] The container has to be registered statically on ProcessContainerDelegateInstance.set()

follow up of #76

**Comment by sdorokhova** [comment]
Copied to https://app.camunda.com/jira/browse/CAM-8109
