### ISSUE TITLE
clarify if CamundaBpmRestConfiguration is still needed

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#83]
There is a TODO on the class: " do we still need this configuration? or is it enough when the implementing application extends the CamundaJerseyResourceConfig?"

I do not know where this comes from, but we should investigate

**Comment by hawky-4s-** [comment]
This is a leftover of my inital commit when I hacked it for the community day. I will check it.

**Comment by osteinhauer** [comment]
Btw.: IMHO the rest starter isn't really a spring boot starter. Why that? If I add the starter as dependency I would expect everything is configured and I don't have to define a ``CamundaJerseyResourceConfig`` bean on my own...

**Comment by jangalinski** [comment]
Nice!
