### ISSUE TITLE
release 1.2

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#85]
I did a lot of fixes and enhancements over the last few weeks. I think we are ready for a release, but I need help with #61, I ignored the test and it keeps failing

**Comment by rmoskal** [comment]
When oh when?

**Comment by osteinhauer** [comment]
#61 is closed

**Comment by jangalinski** [comment]
I included 7.5 which fixes most (all?) issues with the webapp except the security issue #88. So I would say: lets go!

**Comment by osteinhauer** [comment]
👍🏻

**Comment by hawky-4s-** [comment]
Done.

**Comment by osteinhauer** [comment]
👍🏻

**Comment by hawky-4s-** [comment]
@osteinhauer , @jangalinski : Anyone wants to write a blogpost for camunda.org?
See https://github.com/camunda/blog.camunda.org on how to do it.

**Comment by rmoskal** [comment]
I might, but I'm using it in a novel way :).

On Fri, Jun 10, 2016 at 9:54 AM hawky-4s- <notifications@github.com> wrote:

> @osteinhauer <https://github.com/osteinhauer> , @jangalinski
> <https://github.com/jangalinski> : Anyone wants to write a blogpost for
> camunda.org?
> See https://github.com/camunda/blog.camunda.org on how to do it.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/camunda/camunda-bpm-spring-boot-starter/issues/85#issuecomment-225187987>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAiTc63rXuhA0Sf6osMD4CKPAKwcqNMKks5qKWyDgaJpZM4IZumE>
> .
>
-- 

______________
Robert Moskal
Most Media
Brooklyn, USA

**Comment by jangalinski** [comment]
Can write blogpost but not til sunday

**Comment by jangalinski** [comment]
Its not on central yet ....

**Comment by jangalinski** [comment]
issue for blog post: #95

**Comment by hawky-4s-** [comment]
Yeah, sorry. Forgot to publish the staging repository. Done.
