### ISSUE TITLE
use ProcessEnginePlugin for engine configuration

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#86]
Idea: replace all CamundaConfigurations with according ProcessEnginePlugin#preInit.

**Comment by osteinhauer** [comment]
See https://github.com/camunda/camunda-bpm-spring-boot-starter/commit/439d0b1c979dc243df88ceaa8cd922a4d03f71a4

**Comment by osteinhauer** [comment]
@jangalinski Did you have a look at the branch? IMHO we should merge soon.

**Comment by jangalinski** [comment]
No, sorry ... but I am using the mechanism in my (not spring-boot related) project currently and its working fine.
Hopefully I will have some time tonight to check.

**Comment by osteinhauer** [comment]
Merged the branch with bfe67e8 but used wrong issue number. Sorry.
