### ISSUE TITLE
Too open permissions (Security issue)

### ISSUE THREAD

**Issue by bdot** [camunda/camunda-bpm-spring-boot-starter#88]
CamundaBpmWebappAutoConfiguration has 
registry.addResourceHandler(new String[]{"/**"}).addResourceLocations(new String[]{"classpath:/", "classpath:/static/"});

This means all resources like (application.xml/yaml) are accessible revealing all sensitive information, which may cause lot of security issue. I think the line should be 
registry.addResourceHandler(new String[]{"/**"}).addResourceLocations(new String[]"classpath:/static/"});

**Comment by hawky-4s-** [comment]
Thanks for reporting this, I will have a look into it.

**Comment by jangalinski** [comment]
just removing the "classpath:/" resource location does not work, then the webapp is not accessible (404). I also tried explicitly allowing "classpath:/app/ and .../api/", same result, does not work.

Seems like a larger issue so I would vote for "known bug" and continue releasing 1.2 asap. Objections?

**Comment by bdot** [comment]
May I know if you managed to review the pull request I sent earlier for this please.

**Comment by jangalinski** [comment]
No, sorry, did not see the PR (somehow it was not linked to this issue).
I now checked it. 

Result: when I call "/app/cockpit/default" directly, the application works, but when I call "/" the configured redirect to the app does not (404). Ideas how to fix this? very convenient way to access the application).

Also: why to you have "classpath:public" (besides api and static)? Shouldn't it be "api"?

**Comment by jangalinski** [comment]
After changing camunda to 7.5 , the webapp does not work with the provided PR anymore, not only the shortcut, everything. Could you have a look into it? For now I would say: publish 1.2 with this known issue and fix as soon as possible.

**Comment by ronalders** [comment]
New PR added, this fixes security issue and optional redirect also works fine

**Comment by jangalinski** [comment]
already fixed in 1.2.0
