### ISSUE TITLE
switch default camunda version to 7.5

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#92]
this will fix #35 and allow using the new features.

After a first (short) check it seems that we wont have to change any code, meaning just switching the version will remain backward compatible to 7.4 (which is the current minimal version for 7.4)

**Comment by qihaiyan** [comment]
any plan to the 1.2 release?

**Comment by jangalinski** [comment]
Ran into problem after setting camunda.version to 7.5.0:

> [ERROR] Failed to execute goal on project camunda-bpm-spring-boot-starter-webapp: Could not 
> resolve dependencies for project org.camunda.bpm.extension:camunda-bpm-spring-boot-starter-
> webapp:jar:1.2.0-SNAPSHOT: Could not find artifact org.camunda.bpm.webapp:camunda-
> webapp:jar:classes:7.5.0

**Comment by hawky-4s-** [comment]
It is available in the public section of Camunda Nexus:
https://app.camunda.com/nexus/content/repositories/camunda-bpm/org/camunda/bpm/webapp/camunda-webapp/7.5.0/
Am 06.06.2016 11:30 schrieb "Jan Galinski" <notifications@github.com>:

**Comment by jangalinski** [comment]
I will have to retry tonight, I am behind a company mirror ...

**Comment by jangalinski** [comment]
So the webapp:classes are only available on camunda-nexus, NOT on maven central? That's bad ... now I have to configure an additional repository and if I am in a company network, I have to ask some nexus/artifactory admin to add the camunda nexus as a repository ....

**Comment by jangalinski** [comment]
You are right ... this is not a new problem ... I just noticed because we are about to use it in a client project.

**Comment by jangalinski** [comment]
fixed by #94
