### ISSUE TITLE
add documention for 1.2.0

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#97]
the docs still refer to SNAPSHOT and camunda 7.4
I guess it has to be created once and pushed?

**Comment by hawky-4s-** [comment]
I have to look into the build to fix it.
There seems to be an issue with the [publish-docs script](https://github.com/camunda/camunda-bpm-spring-boot-starter/blob/master/publish-docs.sh) that it doesn't upload release docs to the correct folder.

**Comment by osteinhauer** [comment]
any news? Version must be 1.2.1 now. @hawky-4s-  can you resolve this by implementing #33?
