### ISSUE TITLE
list extension in official camunda documentation

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#99]
I just found out that spring boot is missing on the extension-list: https://docs.camunda.org/manual/7.4/introduction/extensions/

what a shame.

**Comment by meyerdan** [comment]
:scream: 

I'll add it right away

**Comment by meyerdan** [comment]
For tracking https://app.camunda.com/jira/browse/CAM-6264

**Comment by meyerdan** [comment]
done
